-- EVE Algo Lab v1
-- Run this entire file once in Supabase: SQL Editor -> New query -> Run.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.market_candles (
  symbol text not null,
  interval text not null,
  candle_time timestamptz not null,
  open numeric(24,10) not null,
  high numeric(24,10) not null,
  low numeric(24,10) not null,
  close numeric(24,10) not null,
  volume numeric(28,8),
  source text not null default 'twelve_data',
  is_complete boolean not null default true,
  ingested_at timestamptz not null default now(),
  primary key (symbol, interval, candle_time),
  constraint market_candles_ohlc_check check (
    high >= greatest(open, close, low)
    and low <= least(open, close, high)
  )
);

create index if not exists market_candles_lookup_idx
  on public.market_candles (symbol, interval, candle_time desc);

create table if not exists public.ingestion_state (
  symbol text not null,
  interval text not null,
  status text not null default 'not_started'
    check (status in ('not_started','queued','downloading','syncing','complete','paused','error')),
  earliest_available timestamptz,
  latest_stored timestamptz,
  oldest_stored timestamptz,
  next_end_time timestamptz,
  rows_processed bigint not null default 0,
  rows_in_database bigint not null default 0,
  estimated_total bigint,
  batches_completed integer not null default 0,
  progress_percent numeric(7,3) not null default 0,
  last_success_at timestamptz,
  last_error text,
  updated_at timestamptz not null default now(),
  primary key (symbol, interval)
);

drop trigger if exists ingestion_state_updated_at on public.ingestion_state;
create trigger ingestion_state_updated_at
before update on public.ingestion_state
for each row execute function public.set_updated_at();

create table if not exists public.ingestion_jobs (
  id uuid primary key default gen_random_uuid(),
  job_type text not null check (job_type in ('backfill','sync_latest','gap_scan')),
  symbol text not null,
  interval text not null,
  status text not null default 'queued'
    check (status in ('queued','running','complete','failed','cancelled')),
  progress_percent numeric(7,3) not null default 0,
  message text,
  parameters jsonb not null default '{}'::jsonb,
  requested_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz,
  heartbeat_at timestamptz,
  worker_id text,
  error text
);

create index if not exists ingestion_jobs_queue_idx
  on public.ingestion_jobs (status, requested_at);

create index if not exists ingestion_state_status_interval_idx
  on public.ingestion_state (status, interval, updated_at desc);

create index if not exists ingestion_jobs_interval_recent_idx
  on public.ingestion_jobs (symbol, interval, requested_at desc);

create table if not exists public.data_gaps (
  id bigint generated by default as identity primary key,
  symbol text not null,
  interval text not null,
  gap_start timestamptz not null,
  gap_end timestamptz not null,
  missing_bars integer not null,
  classification text not null default 'review'
    check (classification in ('review','expected_market_closure','repaired')),
  detected_at timestamptz not null default now(),
  unique (symbol, interval, gap_start, gap_end)
);

create index if not exists data_gaps_lookup_idx
  on public.data_gaps (symbol, interval, classification, gap_start desc);

create table if not exists public.system_events (
  id bigint generated by default as identity primary key,
  level text not null default 'info' check (level in ('info','warning','error','success')),
  component text not null,
  message text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists system_events_recent_idx
  on public.system_events (created_at desc);

-- Strategy/backtest foundation. The first release does not yet run the user's
-- momentum bot until its exact source/rules are imported, but all result storage is ready.
create table if not exists public.strategies (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  description text,
  status text not null default 'draft'
    check (status in ('draft','testing','paper','approved','retired')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists strategies_updated_at on public.strategies;
create trigger strategies_updated_at
before update on public.strategies
for each row execute function public.set_updated_at();

create table if not exists public.strategy_versions (
  id uuid primary key default gen_random_uuid(),
  strategy_id uuid not null references public.strategies(id) on delete cascade,
  version text not null,
  rules jsonb not null default '{}'::jsonb,
  source_sha256 text,
  notes text,
  created_at timestamptz not null default now(),
  unique (strategy_id, version)
);

create table if not exists public.backtest_runs (
  id uuid primary key default gen_random_uuid(),
  strategy_version_id uuid references public.strategy_versions(id) on delete set null,
  name text not null,
  symbol text not null,
  interval text not null,
  resolution text not null default 'candle'
    check (resolution in ('candle','m1_replay','tick')),
  status text not null default 'queued'
    check (status in ('queued','running','complete','failed','cancelled')),
  date_from timestamptz,
  date_to timestamptz,
  starting_balance numeric(18,2),
  ending_balance numeric(18,2),
  net_profit numeric(18,2),
  gross_profit numeric(18,2),
  gross_loss numeric(18,2),
  profit_factor numeric(12,5),
  max_balance_drawdown numeric(18,2),
  max_equity_drawdown numeric(18,2),
  max_drawdown_percent numeric(12,5),
  total_positions integer,
  total_baskets integer,
  winning_baskets integer,
  losing_baskets integer,
  basket_win_rate numeric(12,5),
  expectancy numeric(18,6),
  recovery_factor numeric(12,5),
  settings jsonb not null default '{}'::jsonb,
  reliability jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz,
  error text
);

create table if not exists public.backtest_trades (
  id bigint generated by default as identity primary key,
  backtest_run_id uuid not null references public.backtest_runs(id) on delete cascade,
  basket_id text,
  position_id text,
  side text not null check (side in ('buy','sell')),
  opened_at timestamptz not null,
  closed_at timestamptz,
  entry_price numeric(24,10) not null,
  exit_price numeric(24,10),
  stop_loss numeric(24,10),
  take_profit numeric(24,10),
  lot_size numeric(18,6),
  gross_pnl numeric(18,6),
  costs numeric(18,6) not null default 0,
  net_pnl numeric(18,6),
  exit_reason text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists backtest_trades_run_idx
  on public.backtest_trades (backtest_run_id, opened_at);

-- Atomically claim one queued job. Useful if Railway is later scaled to more workers.
create or replace function public.claim_next_ingestion_job(p_worker_id text)
returns setof public.ingestion_jobs
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  select id into v_id
  from public.ingestion_jobs
  where status = 'queued'
  order by requested_at
  for update skip locked
  limit 1;

  if v_id is null then
    return;
  end if;

  return query
  update public.ingestion_jobs
  set status = 'running',
      started_at = coalesce(started_at, now()),
      heartbeat_at = now(),
      worker_id = p_worker_id,
      message = 'Job claimed by Railway worker'
  where id = v_id
  returning *;
end;
$$;

-- Refresh exact candle bounds/count at sensible checkpoints rather than counting on every dashboard load.
create or replace function public.refresh_ingestion_state(p_symbol text, p_interval text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count bigint;
  v_min timestamptz;
  v_max timestamptz;
begin
  select count(*), min(candle_time), max(candle_time)
  into v_count, v_min, v_max
  from public.market_candles
  where symbol = p_symbol and interval = p_interval;

  insert into public.ingestion_state (
    symbol, interval, rows_in_database, oldest_stored, latest_stored, updated_at
  ) values (
    p_symbol, p_interval, v_count, v_min, v_max, now()
  )
  on conflict (symbol, interval) do update set
    rows_in_database = excluded.rows_in_database,
    oldest_stored = excluded.oldest_stored,
    latest_stored = excluded.latest_stored,
    updated_at = now();
end;
$$;

create or replace function public.scan_market_gaps(
  p_symbol text,
  p_interval text,
  p_interval_seconds integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_total integer;
  v_review integer;
  v_expected integer;
  v_repaired integer;
  v_review_missing bigint;
  v_expected_missing bigint;
begin
  delete from public.data_gaps
  where symbol = p_symbol
    and interval = p_interval
    and classification <> 'repaired';

  with ordered as (
    select
      candle_time,
      lead(candle_time) over (order by candle_time) as next_time
    from public.market_candles
    where symbol = p_symbol and interval = p_interval
  ), measured as (
    select
      candle_time as gap_start,
      next_time as gap_end,
      extract(epoch from (next_time - candle_time)) as gap_seconds,
      greatest(
        floor(extract(epoch from (next_time - candle_time)) / p_interval_seconds)::integer - 1,
        1
      ) as missing_bars
    from ordered
    where next_time is not null
      and extract(epoch from (next_time - candle_time)) > (p_interval_seconds * 1.5)
  ), gaps as (
    select
      gap_start,
      gap_end,
      missing_bars,
      case
        -- Long closures are normally weekends or holidays.
        when gap_seconds >= 21600 then 'expected_market_closure'
        -- Explicit Friday/weekend transition protection.
        when extract(isodow from gap_start at time zone 'UTC') in (5,6,7)
          and extract(isodow from gap_end at time zone 'UTC') in (1,2,7)
          then 'expected_market_closure'
        -- Gold commonly has a daily maintenance break around the late UTC evening.
        -- Keep this narrow: 30 minutes to 3 hours and around 20:00–23:59 UTC.
        when gap_seconds between 1800 and 10800
          and (
            extract(hour from gap_start at time zone 'UTC') between 20 and 23
            or extract(hour from gap_end at time zone 'UTC') between 20 and 23
          )
          then 'expected_market_closure'
        else 'review'
      end as classification
    from measured
  )
  insert into public.data_gaps (
    symbol, interval, gap_start, gap_end, missing_bars, classification
  )
  select p_symbol, p_interval, gap_start, gap_end, missing_bars, classification
  from gaps
  on conflict (symbol, interval, gap_start, gap_end) do update set
    missing_bars = excluded.missing_bars,
    classification = case
      when data_gaps.classification = 'repaired' then 'repaired'
      else excluded.classification
    end,
    detected_at = now();

  select
    count(*),
    count(*) filter (where classification = 'review'),
    count(*) filter (where classification = 'expected_market_closure'),
    count(*) filter (where classification = 'repaired'),
    coalesce(sum(missing_bars) filter (where classification = 'review'), 0),
    coalesce(sum(missing_bars) filter (where classification = 'expected_market_closure'), 0)
  into
    v_total,
    v_review,
    v_expected,
    v_repaired,
    v_review_missing,
    v_expected_missing
  from public.data_gaps
  where symbol = p_symbol and interval = p_interval;

  return jsonb_build_object(
    'total', v_total,
    'review', v_review,
    'expected', v_expected,
    'repaired', v_repaired,
    'review_missing_bars', v_review_missing,
    'expected_missing_bars', v_expected_missing
  );
end;
$$;

create or replace function public.get_market_dashboard(p_symbol text, p_interval text)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'state', coalesce((
      select to_jsonb(s) from public.ingestion_state s
      where s.symbol = p_symbol and s.interval = p_interval
    ), '{}'::jsonb),
    'latest_job', coalesce((
      select to_jsonb(j) from public.ingestion_jobs j
      where j.symbol = p_symbol and j.interval = p_interval
      order by requested_at desc limit 1
    ), '{}'::jsonb),
    'latest_candle', coalesce((
      select to_jsonb(c) from public.market_candles c
      where c.symbol = p_symbol and c.interval = p_interval
      order by candle_time desc limit 1
    ), '{}'::jsonb),
    'gaps', jsonb_build_object(
      'total', (select count(*) from public.data_gaps g where g.symbol = p_symbol and g.interval = p_interval),
      'review', (select count(*) from public.data_gaps g where g.symbol = p_symbol and g.interval = p_interval and g.classification = 'review'),
      'expected', (select count(*) from public.data_gaps g where g.symbol = p_symbol and g.interval = p_interval and g.classification = 'expected_market_closure'),
      'repaired', (select count(*) from public.data_gaps g where g.symbol = p_symbol and g.interval = p_interval and g.classification = 'repaired'),
      'review_missing_bars', (select coalesce(sum(g.missing_bars), 0) from public.data_gaps g where g.symbol = p_symbol and g.interval = p_interval and g.classification = 'review'),
      'expected_missing_bars', (select coalesce(sum(g.missing_bars), 0) from public.data_gaps g where g.symbol = p_symbol and g.interval = p_interval and g.classification = 'expected_market_closure')
    ),
    'events', coalesce((
      select jsonb_agg(to_jsonb(e) order by e.created_at desc)
      from (
        select * from public.system_events
        order by created_at desc limit 12
      ) e
    ), '[]'::jsonb)
  );
$$;

-- RLS is deliberately enabled. The Railway service uses the Supabase service-role key.
alter table public.market_candles enable row level security;
alter table public.ingestion_state enable row level security;
alter table public.ingestion_jobs enable row level security;
alter table public.data_gaps enable row level security;
alter table public.system_events enable row level security;
alter table public.strategies enable row level security;
alter table public.strategy_versions enable row level security;
alter table public.backtest_runs enable row level security;
alter table public.backtest_trades enable row level security;

revoke all on function public.claim_next_ingestion_job(text) from public, anon, authenticated;
revoke all on function public.refresh_ingestion_state(text, text) from public, anon, authenticated;
revoke all on function public.scan_market_gaps(text, text, integer) from public, anon, authenticated;
revoke all on function public.get_market_dashboard(text, text) from public, anon, authenticated;

grant execute on function public.claim_next_ingestion_job(text) to service_role;
grant execute on function public.refresh_ingestion_state(text, text) to service_role;
grant execute on function public.scan_market_gaps(text, text, integer) to service_role;
grant execute on function public.get_market_dashboard(text, text) to service_role;

-- Added in v1.2
create table if not exists public.backtest_baskets (
  id bigint generated by default as identity primary key,
  backtest_run_id uuid not null references public.backtest_runs(id) on delete cascade,
  basket_id text not null,
  opened_at timestamptz not null,
  closed_at timestamptz not null,
  side text not null check (side in ('buy','sell','mixed','none')),
  positions integer not null default 0,
  gross_pnl numeric(18,6) not null default 0,
  costs numeric(18,6) not null default 0,
  net_pnl numeric(18,6) not null default 0,
  peak_floating numeric(18,6) not null default 0,
  worst_floating numeric(18,6) not null default 0,
  max_positions integer not null default 0,
  exit_reason text,
  metadata jsonb not null default '{}'::jsonb,
  unique (backtest_run_id, basket_id)
);
create index if not exists backtest_baskets_run_idx on public.backtest_baskets (backtest_run_id, opened_at desc);
alter table public.backtest_baskets enable row level security;

-- Added in v1.3
create index if not exists market_candles_forward_replay_idx
  on public.market_candles (symbol, interval, candle_time asc)
  include (open, high, low, close, volume);

create index if not exists backtest_runs_resolution_recent_idx
  on public.backtest_runs (resolution, created_at desc);

create index if not exists backtest_runs_active_idx
  on public.backtest_runs (status, created_at desc)
  where status in ('queued', 'running');
-- EVE Algo Lab v1.5 — Learning Foundation
-- Run this entire file once in Supabase SQL Editor before deploying v1.5.
-- Existing candles, ingestion history and backtests are preserved.

create table if not exists public.learning_runs (
  id uuid primary key default gen_random_uuid(),
  symbol text not null default 'XAU/USD',
  source_interval text not null default '5min',
  snapshot_interval text not null default '15min',
  status text not null default 'queued'
    check (status in ('queued','running','complete','failed','cancelled')),
  stage text not null default 'queued',
  progress_percent numeric(7,3) not null default 0,
  message text,
  full_rebuild boolean not null default false,
  cursor_time timestamptz,
  source_rows_scanned bigint not null default 0,
  snapshots_written bigint not null default 0,
  outcome_labels_written bigint not null default 0,
  questions_generated integer not null default 0,
  discoveries_created integer not null default 0,
  requested_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz,
  heartbeat_at timestamptz,
  worker_id text,
  error text
);

create index if not exists learning_runs_queue_idx
  on public.learning_runs (status, requested_at);
create index if not exists learning_runs_recent_idx
  on public.learning_runs (symbol, snapshot_interval, requested_at desc);

create table if not exists public.learning_state (
  symbol text not null,
  snapshot_interval text not null default '15min',
  status text not null default 'not_started'
    check (status in ('not_started','queued','building','ready','error')),
  feature_version text not null default 'eve-features-v1',
  initial_build_complete boolean not null default false,
  auto_update_enabled boolean not null default true,
  last_snapshot_time timestamptz,
  source_latest_time timestamptz,
  snapshots_count bigint not null default 0,
  complete_outcomes_count bigint not null default 0,
  outcome_labels_count bigint not null default 0,
  calendar_stat_count integer not null default 0,
  question_count integer not null default 0,
  discovery_count integer not null default 0,
  prediction_count bigint not null default 0,
  graded_prediction_count bigint not null default 0,
  approved_model_key text,
  challenger_model_key text,
  last_run_id uuid references public.learning_runs(id) on delete set null,
  last_success_at timestamptz,
  last_error text,
  updated_at timestamptz not null default now(),
  primary key (symbol, snapshot_interval)
);

drop trigger if exists learning_state_updated_at on public.learning_state;
create trigger learning_state_updated_at
before update on public.learning_state
for each row execute function public.set_updated_at();

create table if not exists public.market_learning_snapshots (
  symbol text not null,
  snapshot_interval text not null default '15min',
  source_interval text not null default '5min',
  candle_time timestamptz not null,
  open double precision not null,
  high double precision not null,
  low double precision not null,
  close double precision not null,
  volume double precision,
  weekday smallint not null check (weekday between 1 and 7),
  month smallint not null check (month between 1 and 12),
  quarter smallint not null check (quarter between 1 and 4),
  hour_utc smallint not null check (hour_utc between 0 and 23),
  week_of_month smallint not null check (week_of_month between 1 and 6),
  session text not null,
  direction smallint not null check (direction between -1 and 1),
  range_price double precision not null,
  body_price double precision not null,
  upper_wick double precision not null,
  lower_wick double precision not null,
  close_location double precision,
  atr_14 double precision,
  average_range_12 double precision,
  volatility_12 double precision,
  compression_ratio double precision,
  return_1_pct double precision,
  return_3_pct double precision,
  return_12_pct double precision,
  return_48_pct double precision,
  return_288_pct double precision,
  context_m15_return_pct double precision,
  context_h1_return_pct double precision,
  context_h4_return_pct double precision,
  context_d1_return_pct double precision,
  trend_12_atr double precision,
  trend_48_atr double precision,
  streak smallint not null default 0,
  regime text not null,
  alignment_score smallint not null default 0,
  outcomes jsonb not null default '{}'::jsonb,
  outcome_horizons smallint[] not null default '{}'::smallint[],
  outcome_complete boolean not null default false,
  feature_version text not null default 'eve-features-v1',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (symbol, snapshot_interval, candle_time)
);

create index if not exists market_learning_snapshot_time_idx
  on public.market_learning_snapshots (symbol, snapshot_interval, candle_time desc);
create index if not exists market_learning_calendar_idx
  on public.market_learning_snapshots (weekday, month, hour_utc, session);
create index if not exists market_learning_regime_idx
  on public.market_learning_snapshots (regime, alignment_score, candle_time desc);

drop trigger if exists market_learning_snapshots_updated_at on public.market_learning_snapshots;
create trigger market_learning_snapshots_updated_at
before update on public.market_learning_snapshots
for each row execute function public.set_updated_at();

create table if not exists public.calendar_statistics (
  id bigint generated by default as identity primary key,
  symbol text not null default 'XAU/USD',
  dimension text not null,
  bucket_key text not null,
  bucket_label text not null,
  sample_count integer not null default 0,
  average_range double precision,
  median_range double precision,
  average_range_pct double precision,
  median_range_pct double precision,
  average_return_pct double precision,
  average_absolute_return_pct double precision,
  positive_close_rate double precision,
  directional_day_rate double precision,
  effect_vs_baseline_pct double precision,
  metrics jsonb not null default '{}'::jsonb,
  calculated_from timestamptz,
  calculated_to timestamptz,
  updated_at timestamptz not null default now(),
  unique (symbol, dimension, bucket_key)
);

create index if not exists calendar_statistics_lookup_idx
  on public.calendar_statistics (symbol, dimension, effect_vs_baseline_pct desc);

create table if not exists public.prediction_ledger (
  id uuid primary key default gen_random_uuid(),
  symbol text not null default 'XAU/USD',
  model_key text not null,
  source text not null default 'eve',
  snapshot_time timestamptz not null,
  horizon_minutes integer not null check (horizon_minutes > 0),
  predicted_direction text check (predicted_direction in ('up','down','flat','unclear')),
  probability_up double precision,
  probability_down double precision,
  probability_flat double precision,
  expected_move_atr double precision,
  explanation jsonb not null default '{}'::jsonb,
  status text not null default 'pending'
    check (status in ('pending','graded','void')),
  actual_direction text check (actual_direction in ('up','down','flat','unclear')),
  actual_return_pct double precision,
  actual_max_up_atr double precision,
  actual_max_down_atr double precision,
  brier_score double precision,
  grade jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  graded_at timestamptz
);

create index if not exists prediction_ledger_pending_idx
  on public.prediction_ledger (status, snapshot_time);
create index if not exists prediction_ledger_model_idx
  on public.prediction_ledger (model_key, created_at desc);

create table if not exists public.research_questions (
  id uuid primary key default gen_random_uuid(),
  question_key text not null unique,
  symbol text not null default 'XAU/USD',
  category text not null,
  question text not null,
  rationale text,
  priority integer not null default 50 check (priority between 0 and 100),
  status text not null default 'queued'
    check (status in ('queued','testing','promising','answered','rejected','archived')),
  generated_by text not null default 'eve-learning-foundation',
  evidence jsonb not null default '{}'::jsonb,
  test_definition jsonb not null default '{}'::jsonb,
  sample_count integer,
  effect_size double precision,
  confidence_score double precision,
  generated_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists research_questions_queue_idx
  on public.research_questions (status, priority desc, generated_at desc);

drop trigger if exists research_questions_updated_at on public.research_questions;
create trigger research_questions_updated_at
before update on public.research_questions
for each row execute function public.set_updated_at();

create table if not exists public.discoveries (
  id uuid primary key default gen_random_uuid(),
  discovery_key text not null unique,
  symbol text not null default 'XAU/USD',
  question_id uuid references public.research_questions(id) on delete set null,
  title text not null,
  summary text not null,
  category text not null,
  status text not null default 'exploratory'
    check (status in ('exploratory','promising','validated','rejected','retired')),
  sample_count integer not null default 0,
  effect_size double precision,
  confidence_score double precision,
  stability_score double precision,
  evidence jsonb not null default '{}'::jsonb,
  first_observed_at timestamptz,
  last_observed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists discoveries_status_idx
  on public.discoveries (status, confidence_score desc, created_at desc);

drop trigger if exists discoveries_updated_at on public.discoveries;
create trigger discoveries_updated_at
before update on public.discoveries
for each row execute function public.set_updated_at();

create table if not exists public.model_registry (
  id uuid primary key default gen_random_uuid(),
  model_key text not null unique,
  name text not null,
  model_type text not null,
  role text not null check (role in ('approved','challenger','retired','foundation')),
  status text not null default 'ready'
    check (status in ('building','testing','ready','failed','retired')),
  version text not null,
  trained_from timestamptz,
  trained_to timestamptz,
  feature_version text,
  metrics jsonb not null default '{}'::jsonb,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists model_registry_updated_at on public.model_registry;
create trigger model_registry_updated_at
before update on public.model_registry
for each row execute function public.set_updated_at();

insert into public.model_registry (
  model_key, name, model_type, role, status, version, feature_version, metrics, notes
) values (
  'baseline-statistics-v1',
  'EVE Statistical Baseline',
  'descriptive_statistics',
  'approved',
  'ready',
  '1.0',
  'eve-features-v1',
  '{"purpose":"calibration baseline","predictions_enabled":false}'::jsonb,
  'Foundation model used to measure future challengers. It does not issue live predictions in v1.5.'
)
on conflict (model_key) do update set
  name = excluded.name,
  model_type = excluded.model_type,
  role = excluded.role,
  status = excluded.status,
  version = excluded.version,
  feature_version = excluded.feature_version,
  metrics = excluded.metrics,
  notes = excluded.notes,
  updated_at = now();

insert into public.learning_state (
  symbol, snapshot_interval, approved_model_key
) values (
  'XAU/USD', '15min', 'baseline-statistics-v1'
)
on conflict (symbol, snapshot_interval) do update set
  approved_model_key = coalesce(learning_state.approved_model_key, excluded.approved_model_key),
  updated_at = now();

create or replace function public.claim_next_learning_run(p_worker_id text)
returns setof public.learning_runs
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  select id into v_id
  from public.learning_runs
  where status = 'queued'
  order by requested_at
  for update skip locked
  limit 1;

  if v_id is null then
    return;
  end if;

  return query
  update public.learning_runs
  set status = 'running',
      stage = case when stage = 'queued' then 'preparing' else stage end,
      started_at = coalesce(started_at, now()),
      heartbeat_at = now(),
      worker_id = p_worker_id,
      message = 'Learning run claimed by Railway worker'
  where id = v_id
  returning *;
end;
$$;

create or replace function public.refresh_learning_state(p_symbol text, p_snapshot_interval text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_snapshots bigint;
  v_complete bigint;
  v_labels bigint;
  v_latest timestamptz;
  v_source_latest timestamptz;
  v_calendar integer;
  v_questions integer;
  v_discoveries integer;
  v_predictions bigint;
  v_graded bigint;
begin
  select
    count(*),
    count(*) filter (where outcome_complete),
    coalesce(sum(cardinality(outcome_horizons)), 0),
    max(candle_time)
  into v_snapshots, v_complete, v_labels, v_latest
  from public.market_learning_snapshots
  where symbol = p_symbol and snapshot_interval = p_snapshot_interval;

  select max(candle_time) into v_source_latest
  from public.market_candles
  where symbol = p_symbol and interval = '5min';

  select count(*) into v_calendar
  from public.calendar_statistics where symbol = p_symbol;
  select count(*) into v_questions
  from public.research_questions where symbol = p_symbol;
  select count(*) into v_discoveries
  from public.discoveries where symbol = p_symbol;
  select count(*), count(*) filter (where status = 'graded')
  into v_predictions, v_graded
  from public.prediction_ledger where symbol = p_symbol;

  insert into public.learning_state (
    symbol, snapshot_interval, snapshots_count, complete_outcomes_count,
    outcome_labels_count, last_snapshot_time, source_latest_time,
    calendar_stat_count, question_count, discovery_count,
    prediction_count, graded_prediction_count, updated_at
  ) values (
    p_symbol, p_snapshot_interval, v_snapshots, v_complete,
    v_labels, v_latest, v_source_latest,
    v_calendar, v_questions, v_discoveries,
    v_predictions, v_graded, now()
  )
  on conflict (symbol, snapshot_interval) do update set
    snapshots_count = excluded.snapshots_count,
    complete_outcomes_count = excluded.complete_outcomes_count,
    outcome_labels_count = excluded.outcome_labels_count,
    last_snapshot_time = excluded.last_snapshot_time,
    source_latest_time = excluded.source_latest_time,
    calendar_stat_count = excluded.calendar_stat_count,
    question_count = excluded.question_count,
    discovery_count = excluded.discovery_count,
    prediction_count = excluded.prediction_count,
    graded_prediction_count = excluded.graded_prediction_count,
    updated_at = now();
end;
$$;

create or replace function public.get_learning_dashboard(p_symbol text, p_snapshot_interval text)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'state', coalesce((
      select to_jsonb(s) from public.learning_state s
      where s.symbol = p_symbol and s.snapshot_interval = p_snapshot_interval
    ), '{}'::jsonb),
    'latest_run', coalesce((
      select to_jsonb(r) from public.learning_runs r
      where r.symbol = p_symbol and r.snapshot_interval = p_snapshot_interval
      order by requested_at desc limit 1
    ), '{}'::jsonb),
    'approved_model', coalesce((
      select to_jsonb(m) from public.model_registry m
      where m.model_key = (
        select approved_model_key from public.learning_state
        where symbol = p_symbol and snapshot_interval = p_snapshot_interval
      ) limit 1
    ), '{}'::jsonb),
    'challenger_model', coalesce((
      select to_jsonb(m) from public.model_registry m
      where m.model_key = (
        select challenger_model_key from public.learning_state
        where symbol = p_symbol and snapshot_interval = p_snapshot_interval
      ) limit 1
    ), '{}'::jsonb),
    'calendar_statistics', coalesce((
      select jsonb_agg(to_jsonb(c) order by c.dimension, c.bucket_key)
      from public.calendar_statistics c
      where c.symbol = p_symbol
    ), '[]'::jsonb),
    'questions', coalesce((
      select jsonb_agg(to_jsonb(q) order by q.priority desc, q.generated_at desc)
      from (
        select * from public.research_questions
        where symbol = p_symbol and status <> 'archived'
        order by priority desc, generated_at desc limit 12
      ) q
    ), '[]'::jsonb),
    'discoveries', coalesce((
      select jsonb_agg(to_jsonb(d) order by d.confidence_score desc nulls last, d.created_at desc)
      from (
        select * from public.discoveries
        where symbol = p_symbol and status not in ('rejected','retired')
        order by confidence_score desc nulls last, created_at desc limit 12
      ) d
    ), '[]'::jsonb)
  );
$$;

alter table public.learning_runs enable row level security;
alter table public.learning_state enable row level security;
alter table public.market_learning_snapshots enable row level security;
alter table public.calendar_statistics enable row level security;
alter table public.prediction_ledger enable row level security;
alter table public.research_questions enable row level security;
alter table public.discoveries enable row level security;
alter table public.model_registry enable row level security;

revoke all on function public.claim_next_learning_run(text) from public, anon, authenticated;
revoke all on function public.refresh_learning_state(text, text) from public, anon, authenticated;
revoke all on function public.get_learning_dashboard(text, text) from public, anon, authenticated;

grant execute on function public.claim_next_learning_run(text) to service_role;
grant execute on function public.refresh_learning_state(text, text) to service_role;
grant execute on function public.get_learning_dashboard(text, text) to service_role;

-- EVE Algo Lab v1.6 — Autonomous Learning Engine
-- Run this entire file once in Supabase SQL Editor before deploying v1.6.
-- Existing candles, learning snapshots, research, discoveries and backtests are preserved.

alter table public.learning_state
  add column if not exists autonomous_learning_enabled boolean not null default true,
  add column if not exists autonomous_status text not null default 'waiting',
  add column if not exists auto_cycle_interval_minutes integer not null default 15,
  add column if not exists last_auto_cycle_at timestamptz,
  add column if not exists next_auto_cycle_at timestamptz,
  add column if not exists last_incremental_learning_at timestamptz,
  add column if not exists last_research_cycle_at timestamptz,
  add column if not exists last_model_training_at timestamptz,
  add column if not exists pending_outcomes_count bigint not null default 0,
  add column if not exists predictions_pending_count bigint not null default 0,
  add column if not exists questions_tested_total bigint not null default 0,
  add column if not exists questions_tested_last_cycle integer not null default 0,
  add column if not exists discoveries_promising_count integer not null default 0,
  add column if not exists discoveries_validated_count integer not null default 0,
  add column if not exists discoveries_rejected_count integer not null default 0,
  add column if not exists model_promotions_count integer not null default 0,
  add column if not exists last_auto_message text,
  add column if not exists last_auto_error text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'learning_state_autonomous_status_check'
      and conrelid = 'public.learning_state'::regclass
  ) then
    alter table public.learning_state
      add constraint learning_state_autonomous_status_check
      check (autonomous_status in ('waiting','active','researching','training','paused','error'));
  end if;
end $$;

alter table public.model_registry
  add column if not exists artifact jsonb not null default '{}'::jsonb,
  add column if not exists training_rows bigint not null default 0,
  add column if not exists validation_rows bigint not null default 0,
  add column if not exists test_rows bigint not null default 0,
  add column if not exists promotable boolean not null default false,
  add column if not exists promotion_reason text,
  add column if not exists parent_model_key text,
  add column if not exists promoted_at timestamptz,
  add column if not exists evaluation_period jsonb not null default '{}'::jsonb;

create unique index if not exists prediction_ledger_unique_prediction_idx
  on public.prediction_ledger (symbol, model_key, snapshot_time, horizon_minutes);

create table if not exists public.autonomous_runs (
  id uuid primary key default gen_random_uuid(),
  symbol text not null default 'XAU/USD',
  cycle_type text not null default 'full_cycle'
    check (cycle_type in ('full_cycle','incremental_learning','research','model_training','prediction','diagnostic')),
  trigger_source text not null default 'scheduled'
    check (trigger_source in ('scheduled','manual','startup','recovery')),
  status text not null default 'running'
    check (status in ('queued','running','complete','failed','skipped')),
  stage text not null default 'starting',
  message text,
  metrics jsonb not null default '{}'::jsonb,
  worker_id text,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  heartbeat_at timestamptz,
  error text
);

create index if not exists autonomous_runs_recent_idx
  on public.autonomous_runs (symbol, started_at desc);
create index if not exists autonomous_runs_status_idx
  on public.autonomous_runs (status, started_at desc);

create table if not exists public.autonomous_research_reports (
  id uuid primary key default gen_random_uuid(),
  symbol text not null default 'XAU/USD',
  report_date date not null,
  cycle_started_at timestamptz not null default now(),
  questions_tested integer not null default 0,
  questions_rejected integer not null default 0,
  discoveries_promising integer not null default 0,
  discoveries_validated integer not null default 0,
  summary text not null,
  metrics jsonb not null default '{}'::jsonb,
  findings jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (symbol, report_date)
);

create index if not exists autonomous_research_reports_recent_idx
  on public.autonomous_research_reports (symbol, report_date desc);

drop trigger if exists autonomous_research_reports_updated_at on public.autonomous_research_reports;
create trigger autonomous_research_reports_updated_at
before update on public.autonomous_research_reports
for each row execute function public.set_updated_at();

create or replace function public.refresh_autonomous_learning_state(
  p_symbol text,
  p_snapshot_interval text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pending_outcomes bigint;
  v_pending_predictions bigint;
  v_questions_tested bigint;
  v_questions_last integer;
  v_promising integer;
  v_validated integer;
  v_rejected integer;
  v_last_cycle timestamptz;
  v_last_message text;
begin
  select count(*) into v_pending_outcomes
  from public.market_learning_snapshots
  where symbol = p_symbol
    and snapshot_interval = p_snapshot_interval
    and outcome_complete = false;

  select count(*) into v_pending_predictions
  from public.prediction_ledger
  where symbol = p_symbol and status = 'pending';

  select coalesce(sum(coalesce((metrics->>'questions_tested')::bigint, 0)), 0)
  into v_questions_tested
  from public.autonomous_runs
  where symbol = p_symbol and status = 'complete';

  select
    coalesce((metrics->>'questions_tested')::integer, 0),
    started_at,
    message
  into v_questions_last, v_last_cycle, v_last_message
  from public.autonomous_runs
  where symbol = p_symbol
  order by started_at desc
  limit 1;

  select count(*) filter (where status = 'promising'),
         count(*) filter (where status = 'validated'),
         count(*) filter (where status = 'rejected')
  into v_promising, v_validated, v_rejected
  from public.discoveries
  where symbol = p_symbol;

  update public.learning_state
  set pending_outcomes_count = coalesce(v_pending_outcomes, 0),
      predictions_pending_count = coalesce(v_pending_predictions, 0),
      questions_tested_total = coalesce(v_questions_tested, 0),
      questions_tested_last_cycle = coalesce(v_questions_last, 0),
      discoveries_promising_count = coalesce(v_promising, 0),
      discoveries_validated_count = coalesce(v_validated, 0),
      discoveries_rejected_count = coalesce(v_rejected, 0),
      last_auto_cycle_at = coalesce(v_last_cycle, last_auto_cycle_at),
      last_auto_message = coalesce(v_last_message, last_auto_message),
      updated_at = now()
  where symbol = p_symbol and snapshot_interval = p_snapshot_interval;
end;
$$;

create or replace function public.get_learning_dashboard(p_symbol text, p_snapshot_interval text)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'state', coalesce((
      select to_jsonb(s) from public.learning_state s
      where s.symbol = p_symbol and s.snapshot_interval = p_snapshot_interval
    ), '{}'::jsonb),
    'latest_run', coalesce((
      select to_jsonb(r) from public.learning_runs r
      where r.symbol = p_symbol and r.snapshot_interval = p_snapshot_interval
      order by requested_at desc limit 1
    ), '{}'::jsonb),
    'latest_autonomous_run', coalesce((
      select to_jsonb(a) from public.autonomous_runs a
      where a.symbol = p_symbol
      order by started_at desc limit 1
    ), '{}'::jsonb),
    'approved_model', coalesce((
      select to_jsonb(m) - 'artifact' from public.model_registry m
      where m.model_key = (
        select approved_model_key from public.learning_state
        where symbol = p_symbol and snapshot_interval = p_snapshot_interval
      ) limit 1
    ), '{}'::jsonb),
    'challenger_model', coalesce((
      select to_jsonb(m) - 'artifact' from public.model_registry m
      where m.model_key = (
        select challenger_model_key from public.learning_state
        where symbol = p_symbol and snapshot_interval = p_snapshot_interval
      ) limit 1
    ), '{}'::jsonb),
    'calendar_statistics', coalesce((
      select jsonb_agg(to_jsonb(c) order by c.dimension, c.bucket_key)
      from public.calendar_statistics c
      where c.symbol = p_symbol
    ), '[]'::jsonb),
    'questions', coalesce((
      select jsonb_agg(to_jsonb(q) order by q.priority desc, q.generated_at desc)
      from (
        select * from public.research_questions
        where symbol = p_symbol and status <> 'archived'
        order by priority desc, generated_at desc limit 20
      ) q
    ), '[]'::jsonb),
    'discoveries', coalesce((
      select jsonb_agg(to_jsonb(d) order by d.confidence_score desc nulls last, d.created_at desc)
      from (
        select * from public.discoveries
        where symbol = p_symbol and status not in ('retired')
        order by
          case status when 'validated' then 1 when 'promising' then 2 when 'exploratory' then 3 else 4 end,
          confidence_score desc nulls last,
          created_at desc
        limit 20
      ) d
    ), '[]'::jsonb),
    'research_reports', coalesce((
      select jsonb_agg(to_jsonb(r) order by r.report_date desc)
      from (
        select * from public.autonomous_research_reports
        where symbol = p_symbol
        order by report_date desc limit 7
      ) r
    ), '[]'::jsonb),
    'recent_predictions', coalesce((
      select jsonb_agg(to_jsonb(p) order by p.snapshot_time desc, p.horizon_minutes)
      from (
        select * from public.prediction_ledger
        where symbol = p_symbol
        order by snapshot_time desc, horizon_minutes
        limit 18
      ) p
    ), '[]'::jsonb)
  );
$$;

update public.learning_state
set autonomous_learning_enabled = true,
    autonomous_status = case when initial_build_complete then 'active' else 'waiting' end,
    auto_cycle_interval_minutes = 15,
    last_auto_message = case
      when initial_build_complete then 'Autonomous v1.6 learning will start after Railway redeploys.'
      else 'Build the initial learning foundation once; autonomy starts immediately afterwards.'
    end,
    updated_at = now()
where symbol = 'XAU/USD' and snapshot_interval = '15min';

alter table public.autonomous_runs enable row level security;
alter table public.autonomous_research_reports enable row level security;

revoke all on function public.refresh_autonomous_learning_state(text, text) from public, anon, authenticated;
revoke all on function public.get_learning_dashboard(text, text) from public, anon, authenticated;

grant execute on function public.refresh_autonomous_learning_state(text, text) to service_role;
grant execute on function public.get_learning_dashboard(text, text) to service_role;
-- EVE Algo Lab v1.7 — Continuous Historical Research Worker
-- Run this complete file once in Supabase SQL Editor before deploying v1.7.
-- Existing candles, learning snapshots, discoveries, models and backtests are preserved.

create table if not exists public.historical_research_state (
  symbol text not null default 'XAU/USD',
  snapshot_interval text not null default '15min',
  status text not null default 'waiting'
    check (status in ('waiting','active','loading','researching','paused','error')),
  worker_id text,
  heartbeat_at timestamptz,
  current_job_id uuid,
  current_question text,
  queue_count integer not null default 0,
  running_count integer not null default 0,
  completed_count bigint not null default 0,
  rejected_count bigint not null default 0,
  promising_count bigint not null default 0,
  validated_count bigint not null default 0,
  failed_count bigint not null default 0,
  rows_scanned_total bigint not null default 0,
  jobs_seeded_total bigint not null default 0,
  generator_generation integer not null default 0,
  last_generation_at timestamptz,
  last_job_started_at timestamptz,
  last_job_finished_at timestamptz,
  last_result text,
  last_error text,
  started_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (symbol, snapshot_interval)
);

create table if not exists public.historical_research_jobs (
  id uuid primary key default gen_random_uuid(),
  job_key text not null unique,
  symbol text not null default 'XAU/USD',
  snapshot_interval text not null default '15min',
  generation integer not null default 1,
  priority integer not null default 50 check (priority between 0 and 100),
  category text not null default 'continuous_historical_research',
  question text not null,
  rationale text,
  test_definition jsonb not null default '{}'::jsonb,
  status text not null default 'queued'
    check (status in ('queued','running','complete','failed')),
  result_status text
    check (result_status is null or result_status in ('rejected','promising','validated')),
  rows_scanned bigint not null default 0,
  sample_count integer not null default 0,
  effect_size double precision,
  confidence_score double precision,
  stability_score double precision,
  summary text,
  evidence jsonb not null default '{}'::jsonb,
  worker_id text,
  requested_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz,
  heartbeat_at timestamptz,
  error text
);

create index if not exists historical_research_jobs_queue_idx
  on public.historical_research_jobs (status, priority desc, requested_at);
create index if not exists historical_research_jobs_recent_idx
  on public.historical_research_jobs (symbol, snapshot_interval, finished_at desc nulls last);
create index if not exists historical_research_jobs_result_idx
  on public.historical_research_jobs (result_status, confidence_score desc nulls last);

insert into public.historical_research_state (
  symbol, snapshot_interval, status, last_result
) values (
  'XAU/USD', '15min', 'active',
  'v1.7 is ready to generate and test historical questions continuously on Railway.'
)
on conflict (symbol, snapshot_interval) do update set
  status = 'active',
  last_error = null,
  updated_at = now();

create or replace function public.claim_next_historical_research_job(p_worker_id text)
returns setof public.historical_research_jobs
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  select id into v_id
  from public.historical_research_jobs
  where status = 'queued'
  order by priority desc, requested_at asc
  for update skip locked
  limit 1;

  if v_id is null then
    return;
  end if;

  update public.historical_research_jobs
  set status = 'running',
      worker_id = p_worker_id,
      started_at = coalesce(started_at, now()),
      heartbeat_at = now(),
      error = null
  where id = v_id;

  return query
  select * from public.historical_research_jobs where id = v_id;
end;
$$;

create or replace function public.refresh_historical_research_state(
  p_symbol text,
  p_snapshot_interval text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_queue integer;
  v_running integer;
  v_completed bigint;
  v_rejected bigint;
  v_promising bigint;
  v_validated bigint;
  v_failed bigint;
  v_rows bigint;
  v_seeded bigint;
begin
  select
    count(*) filter (where status = 'queued'),
    count(*) filter (where status = 'running'),
    count(*) filter (where status = 'complete'),
    count(*) filter (where result_status = 'rejected'),
    count(*) filter (where result_status = 'promising'),
    count(*) filter (where result_status = 'validated'),
    count(*) filter (where status = 'failed'),
    coalesce(sum(rows_scanned) filter (where status = 'complete'), 0),
    count(*)
  into
    v_queue, v_running, v_completed, v_rejected, v_promising,
    v_validated, v_failed, v_rows, v_seeded
  from public.historical_research_jobs
  where symbol = p_symbol and snapshot_interval = p_snapshot_interval;

  insert into public.historical_research_state (
    symbol, snapshot_interval, status, queue_count, running_count,
    completed_count, rejected_count, promising_count, validated_count,
    failed_count, rows_scanned_total, jobs_seeded_total, updated_at
  ) values (
    p_symbol, p_snapshot_interval, 'active', coalesce(v_queue,0), coalesce(v_running,0),
    coalesce(v_completed,0), coalesce(v_rejected,0), coalesce(v_promising,0),
    coalesce(v_validated,0), coalesce(v_failed,0), coalesce(v_rows,0),
    coalesce(v_seeded,0), now()
  )
  on conflict (symbol, snapshot_interval) do update set
    queue_count = excluded.queue_count,
    running_count = excluded.running_count,
    completed_count = excluded.completed_count,
    rejected_count = excluded.rejected_count,
    promising_count = excluded.promising_count,
    validated_count = excluded.validated_count,
    failed_count = excluded.failed_count,
    rows_scanned_total = excluded.rows_scanned_total,
    jobs_seeded_total = excluded.jobs_seeded_total,
    updated_at = now();
end;
$$;

create or replace function public.get_historical_research_dashboard(
  p_symbol text,
  p_snapshot_interval text
)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'state', coalesce((
      select to_jsonb(s)
      from public.historical_research_state s
      where s.symbol = p_symbol and s.snapshot_interval = p_snapshot_interval
    ), '{}'::jsonb),
    'current_job', coalesce((
      select to_jsonb(j)
      from public.historical_research_jobs j
      where j.symbol = p_symbol
        and j.snapshot_interval = p_snapshot_interval
        and j.status = 'running'
      order by j.started_at desc limit 1
    ), '{}'::jsonb),
    'latest_job', coalesce((
      select to_jsonb(j)
      from public.historical_research_jobs j
      where j.symbol = p_symbol
        and j.snapshot_interval = p_snapshot_interval
        and j.status in ('complete','failed')
      order by j.finished_at desc nulls last limit 1
    ), '{}'::jsonb),
    'recent_jobs', coalesce((
      select jsonb_agg(to_jsonb(j) order by j.finished_at desc nulls last)
      from (
        select * from public.historical_research_jobs
        where symbol = p_symbol
          and snapshot_interval = p_snapshot_interval
          and status in ('complete','failed')
        order by finished_at desc nulls last
        limit 12
      ) j
    ), '[]'::jsonb)
  );
$$;

alter table public.historical_research_state enable row level security;
alter table public.historical_research_jobs enable row level security;

revoke all on function public.claim_next_historical_research_job(text) from public, anon, authenticated;
revoke all on function public.refresh_historical_research_state(text, text) from public, anon, authenticated;
revoke all on function public.get_historical_research_dashboard(text, text) from public, anon, authenticated;

grant execute on function public.claim_next_historical_research_job(text) to service_role;
grant execute on function public.refresh_historical_research_state(text, text) to service_role;
grant execute on function public.get_historical_research_dashboard(text, text) to service_role;
-- EVE Algo Lab v1.7.1 — Historical worker startup repair
-- Run this complete file once in Supabase SQL Editor.
-- It preserves all candles, learning snapshots, questions, findings and backtests.

-- The v1.7 worker writes heartbeat and job progress through PostgREST using the
-- service-role key. Explicit grants ensure the two new RLS tables are visible to
-- that role instead of returning REST 404 responses.
grant usage on schema public to service_role;
grant select, insert, update, delete on table public.historical_research_state to service_role;
grant select, insert, update, delete on table public.historical_research_jobs to service_role;

-- Recover jobs left running by a Railway restart through a security-definer RPC.
-- v1.7.1 calls this RPC during startup rather than issuing the failing direct PATCH.
create or replace function public.reset_stale_historical_research_jobs(
  p_stale_minutes integer default 20
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  update public.historical_research_jobs
  set status = 'queued',
      worker_id = null,
      started_at = null,
      heartbeat_at = null,
      error = 'Recovered automatically after Railway restart'
  where status = 'running'
    and (
      heartbeat_at is null
      or heartbeat_at < now() - make_interval(mins => greatest(1, p_stale_minutes))
    );

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

revoke all on function public.reset_stale_historical_research_jobs(integer)
  from public, anon, authenticated;
grant execute on function public.reset_stale_historical_research_jobs(integer)
  to service_role;

-- Ensure the state row exists and clear the failed startup message.
insert into public.historical_research_state (
  symbol, snapshot_interval, status, last_result, last_error, updated_at
) values (
  'XAU/USD', '15min', 'active',
  'v1.7.1 storage permissions repaired. Waiting for Railway worker heartbeat.',
  null, now()
)
on conflict (symbol, snapshot_interval) do update set
  status = 'active',
  last_error = null,
  last_result = 'v1.7.1 storage permissions repaired. Waiting for Railway worker heartbeat.',
  updated_at = now();

-- Force Supabase PostgREST to refresh its table/function schema immediately.
notify pgrst, 'reload schema';
