-- EVE Algo Lab v1
-- Run this entire file once in Supabase: SQL Editor -> New query -> Run.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.market_candles (
  symbol text not null,
  interval text not null,
  candle_time timestamptz not null,
  open numeric(24,10) not null,
  high numeric(24,10) not null,
  low numeric(24,10) not null,
  close numeric(24,10) not null,
  volume numeric(28,8),
  source text not null default 'twelve_data',
  is_complete boolean not null default true,
  ingested_at timestamptz not null default now(),
  primary key (symbol, interval, candle_time),
  constraint market_candles_ohlc_check check (
    high >= greatest(open, close, low)
    and low <= least(open, close, high)
  )
);

create index if not exists market_candles_lookup_idx
  on public.market_candles (symbol, interval, candle_time desc);

create table if not exists public.ingestion_state (
  symbol text not null,
  interval text not null,
  status text not null default 'not_started'
    check (status in ('not_started','queued','downloading','syncing','complete','paused','error')),
  earliest_available timestamptz,
  latest_stored timestamptz,
  oldest_stored timestamptz,
  next_end_time timestamptz,
  rows_processed bigint not null default 0,
  rows_in_database bigint not null default 0,
  estimated_total bigint,
  batches_completed integer not null default 0,
  progress_percent numeric(7,3) not null default 0,
  last_success_at timestamptz,
  last_error text,
  updated_at timestamptz not null default now(),
  primary key (symbol, interval)
);

drop trigger if exists ingestion_state_updated_at on public.ingestion_state;
create trigger ingestion_state_updated_at
before update on public.ingestion_state
for each row execute function public.set_updated_at();

create table if not exists public.ingestion_jobs (
  id uuid primary key default gen_random_uuid(),
  job_type text not null check (job_type in ('backfill','sync_latest','gap_scan')),
  symbol text not null,
  interval text not null,
  status text not null default 'queued'
    check (status in ('queued','running','complete','failed','cancelled')),
  progress_percent numeric(7,3) not null default 0,
  message text,
  parameters jsonb not null default '{}'::jsonb,
  requested_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz,
  heartbeat_at timestamptz,
  worker_id text,
  error text
);

create index if not exists ingestion_jobs_queue_idx
  on public.ingestion_jobs (status, requested_at);

create table if not exists public.data_gaps (
  id bigint generated by default as identity primary key,
  symbol text not null,
  interval text not null,
  gap_start timestamptz not null,
  gap_end timestamptz not null,
  missing_bars integer not null,
  classification text not null default 'review'
    check (classification in ('review','expected_market_closure','repaired')),
  detected_at timestamptz not null default now(),
  unique (symbol, interval, gap_start, gap_end)
);

create index if not exists data_gaps_lookup_idx
  on public.data_gaps (symbol, interval, classification, gap_start desc);

create table if not exists public.system_events (
  id bigint generated by default as identity primary key,
  level text not null default 'info' check (level in ('info','warning','error','success')),
  component text not null,
  message text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists system_events_recent_idx
  on public.system_events (created_at desc);

-- Strategy/backtest foundation. The first release does not yet run the user's
-- momentum bot until its exact source/rules are imported, but all result storage is ready.
create table if not exists public.strategies (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  description text,
  status text not null default 'draft'
    check (status in ('draft','testing','paper','approved','retired')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists strategies_updated_at on public.strategies;
create trigger strategies_updated_at
before update on public.strategies
for each row execute function public.set_updated_at();

create table if not exists public.strategy_versions (
  id uuid primary key default gen_random_uuid(),
  strategy_id uuid not null references public.strategies(id) on delete cascade,
  version text not null,
  rules jsonb not null default '{}'::jsonb,
  source_sha256 text,
  notes text,
  created_at timestamptz not null default now(),
  unique (strategy_id, version)
);

create table if not exists public.backtest_runs (
  id uuid primary key default gen_random_uuid(),
  strategy_version_id uuid references public.strategy_versions(id) on delete set null,
  name text not null,
  symbol text not null,
  interval text not null,
  resolution text not null default 'candle'
    check (resolution in ('candle','m1_replay','tick')),
  status text not null default 'queued'
    check (status in ('queued','running','complete','failed','cancelled')),
  date_from timestamptz,
  date_to timestamptz,
  starting_balance numeric(18,2),
  ending_balance numeric(18,2),
  net_profit numeric(18,2),
  gross_profit numeric(18,2),
  gross_loss numeric(18,2),
  profit_factor numeric(12,5),
  max_balance_drawdown numeric(18,2),
  max_equity_drawdown numeric(18,2),
  max_drawdown_percent numeric(12,5),
  total_positions integer,
  total_baskets integer,
  winning_baskets integer,
  losing_baskets integer,
  basket_win_rate numeric(12,5),
  expectancy numeric(18,6),
  recovery_factor numeric(12,5),
  settings jsonb not null default '{}'::jsonb,
  reliability jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz,
  error text
);

create table if not exists public.backtest_trades (
  id bigint generated by default as identity primary key,
  backtest_run_id uuid not null references public.backtest_runs(id) on delete cascade,
  basket_id text,
  position_id text,
  side text not null check (side in ('buy','sell')),
  opened_at timestamptz not null,
  closed_at timestamptz,
  entry_price numeric(24,10) not null,
  exit_price numeric(24,10),
  stop_loss numeric(24,10),
  take_profit numeric(24,10),
  lot_size numeric(18,6),
  gross_pnl numeric(18,6),
  costs numeric(18,6) not null default 0,
  net_pnl numeric(18,6),
  exit_reason text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists backtest_trades_run_idx
  on public.backtest_trades (backtest_run_id, opened_at);

-- Atomically claim one queued job. Useful if Railway is later scaled to more workers.
create or replace function public.claim_next_ingestion_job(p_worker_id text)
returns setof public.ingestion_jobs
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  select id into v_id
  from public.ingestion_jobs
  where status = 'queued'
  order by requested_at
  for update skip locked
  limit 1;

  if v_id is null then
    return;
  end if;

  return query
  update public.ingestion_jobs
  set status = 'running',
      started_at = coalesce(started_at, now()),
      heartbeat_at = now(),
      worker_id = p_worker_id,
      message = 'Job claimed by Railway worker'
  where id = v_id
  returning *;
end;
$$;

-- Refresh exact candle bounds/count at sensible checkpoints rather than counting on every dashboard load.
create or replace function public.refresh_ingestion_state(p_symbol text, p_interval text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count bigint;
  v_min timestamptz;
  v_max timestamptz;
begin
  select count(*), min(candle_time), max(candle_time)
  into v_count, v_min, v_max
  from public.market_candles
  where symbol = p_symbol and interval = p_interval;

  insert into public.ingestion_state (
    symbol, interval, rows_in_database, oldest_stored, latest_stored, updated_at
  ) values (
    p_symbol, p_interval, v_count, v_min, v_max, now()
  )
  on conflict (symbol, interval) do update set
    rows_in_database = excluded.rows_in_database,
    oldest_stored = excluded.oldest_stored,
    latest_stored = excluded.latest_stored,
    updated_at = now();
end;
$$;

create or replace function public.scan_market_gaps(
  p_symbol text,
  p_interval text,
  p_interval_seconds integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_total integer;
  v_review integer;
begin
  delete from public.data_gaps
  where symbol = p_symbol and interval = p_interval and classification <> 'repaired';

  with ordered as (
    select
      candle_time,
      lead(candle_time) over (order by candle_time) as next_time
    from public.market_candles
    where symbol = p_symbol and interval = p_interval
  ), gaps as (
    select
      candle_time as gap_start,
      next_time as gap_end,
      greatest(
        floor(extract(epoch from (next_time - candle_time)) / p_interval_seconds)::integer - 1,
        1
      ) as missing_bars,
      case
        when extract(epoch from (next_time - candle_time)) >= 21600 then 'expected_market_closure'
        when extract(isodow from candle_time at time zone 'UTC') in (5,6,7)
          and extract(isodow from next_time at time zone 'UTC') in (1,2,7)
          then 'expected_market_closure'
        else 'review'
      end as classification
    from ordered
    where next_time is not null
      and extract(epoch from (next_time - candle_time)) > (p_interval_seconds * 1.5)
  )
  insert into public.data_gaps (
    symbol, interval, gap_start, gap_end, missing_bars, classification
  )
  select p_symbol, p_interval, gap_start, gap_end, missing_bars, classification
  from gaps
  on conflict (symbol, interval, gap_start, gap_end) do update set
    missing_bars = excluded.missing_bars,
    classification = excluded.classification,
    detected_at = now();

  select count(*), count(*) filter (where classification = 'review')
  into v_total, v_review
  from public.data_gaps
  where symbol = p_symbol and interval = p_interval;

  return jsonb_build_object('total', v_total, 'review', v_review);
end;
$$;

create or replace function public.get_market_dashboard(p_symbol text, p_interval text)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'state', coalesce((
      select to_jsonb(s) from public.ingestion_state s
      where s.symbol = p_symbol and s.interval = p_interval
    ), '{}'::jsonb),
    'latest_job', coalesce((
      select to_jsonb(j) from public.ingestion_jobs j
      where j.symbol = p_symbol and j.interval = p_interval
      order by requested_at desc limit 1
    ), '{}'::jsonb),
    'latest_candle', coalesce((
      select to_jsonb(c) from public.market_candles c
      where c.symbol = p_symbol and c.interval = p_interval
      order by candle_time desc limit 1
    ), '{}'::jsonb),
    'gaps', jsonb_build_object(
      'total', (select count(*) from public.data_gaps g where g.symbol = p_symbol and g.interval = p_interval),
      'review', (select count(*) from public.data_gaps g where g.symbol = p_symbol and g.interval = p_interval and g.classification = 'review')
    ),
    'events', coalesce((
      select jsonb_agg(to_jsonb(e) order by e.created_at desc)
      from (
        select * from public.system_events
        order by created_at desc limit 12
      ) e
    ), '[]'::jsonb)
  );
$$;

-- RLS is deliberately enabled. The Railway service uses the Supabase service-role key.
alter table public.market_candles enable row level security;
alter table public.ingestion_state enable row level security;
alter table public.ingestion_jobs enable row level security;
alter table public.data_gaps enable row level security;
alter table public.system_events enable row level security;
alter table public.strategies enable row level security;
alter table public.strategy_versions enable row level security;
alter table public.backtest_runs enable row level security;
alter table public.backtest_trades enable row level security;

revoke all on function public.claim_next_ingestion_job(text) from public, anon, authenticated;
revoke all on function public.refresh_ingestion_state(text, text) from public, anon, authenticated;
revoke all on function public.scan_market_gaps(text, text, integer) from public, anon, authenticated;
revoke all on function public.get_market_dashboard(text, text) from public, anon, authenticated;

grant execute on function public.claim_next_ingestion_job(text) to service_role;
grant execute on function public.refresh_ingestion_state(text, text) to service_role;
grant execute on function public.scan_market_gaps(text, text, integer) to service_role;
grant execute on function public.get_market_dashboard(text, text) to service_role;

-- Added in v1.2
create table if not exists public.backtest_baskets (
  id bigint generated by default as identity primary key,
  backtest_run_id uuid not null references public.backtest_runs(id) on delete cascade,
  basket_id text not null,
  opened_at timestamptz not null,
  closed_at timestamptz not null,
  side text not null check (side in ('buy','sell','mixed','none')),
  positions integer not null default 0,
  gross_pnl numeric(18,6) not null default 0,
  costs numeric(18,6) not null default 0,
  net_pnl numeric(18,6) not null default 0,
  peak_floating numeric(18,6) not null default 0,
  worst_floating numeric(18,6) not null default 0,
  max_positions integer not null default 0,
  exit_reason text,
  metadata jsonb not null default '{}'::jsonb,
  unique (backtest_run_id, basket_id)
);
create index if not exists backtest_baskets_run_idx on public.backtest_baskets (backtest_run_id, opened_at desc);
alter table public.backtest_baskets enable row level security;
