from __future__ import annotations

import asyncio
import hashlib
import io
import json
import logging
import re
import socket
import uuid
import zipfile
from datetime import datetime, timezone
from typing import Any

from app.services.autonomy import number
from app.services.learning import SNAPSHOT_INTERVAL
from app.services.demo_eligibility import plain_rule_summary
from app.services.fleet import fleet_token
from app.services.supabase_repo import SupabaseRepository
from app.settings import Settings

logger = logging.getLogger(__name__)

MT5_GENERATOR_VERSION = "mt5-ea-generator-v3.1"
MAX_GENERATION_SEEDS = 20


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


def canonical(value: Any) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), default=str)


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def safe_name(value: str, fallback: str = "EVE_Strategy") -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]+", "_", str(value or "")).strip("_")
    cleaned = re.sub(r"_+", "_", cleaned)
    if not cleaned:
        cleaned = fallback
    if cleaned[0].isdigit():
        cleaned = f"EVE_{cleaned}"
    return cleaned[:80]


def mql_string(value: Any) -> str:
    return str(value).replace("\\", "\\\\").replace('"', '\\"')


def _condition_expression(condition: dict[str, Any]) -> str:
    field = str(condition.get("field") or "")
    value = condition.get("value")
    numeric_fields = {"weekday", "month", "quarter", "week_of_month", "hour_utc", "direction"}
    string_fields = {"session", "regime", "alignment_band", "compression_band", "trend_band", "streak_band"}
    if field in numeric_fields:
        return f"f.{field} == {int(number(value))}"
    if field in string_fields:
        return f'f.{field} == "{mql_string(value)}"'
    raise ValueError(f"Unsupported MT5 source condition field: {field}")


def condition_expression(conditions: list[dict[str, Any]]) -> str:
    if not conditions:
        return "true"
    return " &&\n      ".join(f"({_condition_expression(item)})" for item in conditions)


def _magic_from_hash(rule_hash: str) -> int:
    try:
        raw = int(rule_hash[:8], 16)
    except (TypeError, ValueError):
        raw = 24000001
    return 20000000 + (raw % 70000000)


def _bool_literal(value: bool) -> str:
    return "true" if value else "false"


def generate_mq5_source(frozen: dict[str, Any]) -> str:
    rules = dict(frozen.get("rules") or {})
    rule_hash = str(frozen.get("rule_hash") or "")
    if len(rule_hash) < 16:
        raise ValueError("Frozen strategy has no valid rule hash")

    strategy_code = str(frozen.get("strategy_code") or f"EVE-{rule_hash[:12].upper()}")
    strategy_name = str(frozen.get("name") or strategy_code)
    version = str(frozen.get("version") or "1.0")
    class_name = safe_name(f"{strategy_code}_{version}")
    source_conditions = list(rules.get("source_conditions") or [])
    condition_mode = str(rules.get("condition_mode") or "include")
    direction_rule = str(rules.get("direction_rule") or "current_direction")
    stop_atr = max(0.05, number(rules.get("stop_atr"), 1.0))
    target_atr = max(0.05, number(rules.get("target_atr"), 2.0))
    hold_minutes = max(1, int(number(rules.get("horizon_minutes"), 60)))
    cooldown_minutes = max(1, int(number(rules.get("cooldown_minutes"), hold_minutes)))
    source_match = condition_expression(source_conditions)
    magic = _magic_from_hash(rule_hash)

    if direction_rule not in {"current_direction", "alignment_direction", "fixed_long", "fixed_short"}:
        raise ValueError(f"Unsupported MT5 direction rule: {direction_rule}")
    if condition_mode not in {"include", "exclude"}:
        raise ValueError(f"Unsupported MT5 condition mode: {condition_mode}")

    direction_code = {
        "current_direction": "return f.direction;",
        "alignment_direction": "return SignInt(f.alignment_score);",
        "fixed_long": "return 1;",
        "fixed_short": "return -1;",
    }[direction_rule]

    source = f'''//+------------------------------------------------------------------+
//| {class_name}.mq5
//| Generated by EVE Algo Lab v2.5 from immutable frozen rules.
//| Strategy: {mql_string(strategy_name)}
//| Strategy code: {mql_string(strategy_code)}
//| Frozen version: {mql_string(version)}
//| Rules SHA-256: {mql_string(rule_hash)}
//| GENERATION STATUS: READY FOR METAEDITOR COMPILE AND DEMO TEST ONLY
//| Validation basis: stored M1 replay, cost stress and rule robustness passed.
//+------------------------------------------------------------------+
#property copyright "EVE Algo Lab"
#property link      "https://evealgolab.netlify.app"
#property version   "2.50"
#property strict
#property description "Generated from EVE frozen strategy {mql_string(strategy_code)}"

#include <Trade/Trade.mqh>

input bool   InpEnableTrading             = false;   // Safety lock: turn on only for MT5 demo testing
input bool   InpUseFixedLot               = false;
input double InpFixedLot                  = 0.01;
input double InpRiskPercent               = 0.25;
input double InpMaxDailyLossPercent       = 1.00;
input int    InpMaxSpreadPoints           = 80;
input int    InpSlippagePoints            = 20;
input bool   InpUseAutoBrokerUtcOffset    = true;
input int    InpManualBrokerUtcOffsetHours= 0;
input bool   InpAllowLong                 = true;
input bool   InpAllowShort                = true;
input bool   InpVerboseLogging            = true;

const string EVE_STRATEGY_CODE = "{mql_string(strategy_code)}";
const string EVE_STRATEGY_NAME = "{mql_string(strategy_name)}";
const string EVE_RULE_HASH     = "{mql_string(rule_hash)}";
const string EVE_RULE_VERSION  = "{mql_string(version)}";
const long   EVE_MAGIC         = {magic};
const double EVE_STOP_ATR      = {stop_atr:.8f};
const double EVE_TARGET_ATR    = {target_atr:.8f};
const int    EVE_MAX_HOLD_MIN  = {hold_minutes};
const int    EVE_COOLDOWN_MIN  = {cooldown_minutes};
const bool   EVE_CONDITION_INCLUDE = {_bool_literal(condition_mode == "include")};

CTrade trade;
datetime last_m5_bar = 0;
datetime last_entry_time = 0;

struct FeatureSet
{{
   int weekday;
   int month;
   int quarter;
   int week_of_month;
   int hour_utc;
   string session;
   string regime;
   int direction;
   int alignment_score;
   string alignment_band;
   double compression_ratio;
   string compression_band;
   double trend_12_atr;
   string trend_band;
   int streak;
   string streak_band;
   double atr_14;
}};

int SignDouble(const double value)
{{
   if(value > 1e-12) return 1;
   if(value < -1e-12) return -1;
   return 0;
}}

int SignInt(const int value)
{{
   if(value > 0) return 1;
   if(value < 0) return -1;
   return 0;
}}

bool IsLeapYear(const int year)
{{
   return ((year % 4 == 0 && year % 100 != 0) || year % 400 == 0);
}}

int DaysInMonth(const int year,const int month)
{{
   if(month == 2) return IsLeapYear(year) ? 29 : 28;
   if(month == 4 || month == 6 || month == 9 || month == 11) return 30;
   return 31;
}}

int DayOfWeekUtc(const datetime value)
{{
   MqlDateTime dt;
   TimeToStruct(value,dt);
   return dt.day_of_week;
}}

int LastSunday(const int year,const int month)
{{
   MqlDateTime dt;
   dt.year=year; dt.mon=month; dt.day=DaysInMonth(year,month);
   dt.hour=12; dt.min=0; dt.sec=0;
   datetime t=StructToTime(dt);
   int dow=DayOfWeekUtc(t);
   return dt.day-dow;
}}

int NthSunday(const int year,const int month,const int nth)
{{
   MqlDateTime dt;
   dt.year=year; dt.mon=month; dt.day=1; dt.hour=12; dt.min=0; dt.sec=0;
   datetime t=StructToTime(dt);
   int first_dow=DayOfWeekUtc(t);
   int first_sunday = first_dow == 0 ? 1 : 8-first_dow;
   return first_sunday + (nth-1)*7;
}}

bool IsLondonDstUtc(const datetime utc_time)
{{
   MqlDateTime dt; TimeToStruct(utc_time,dt);
   int start_day=LastSunday(dt.year,3);
   int end_day=LastSunday(dt.year,10);
   MqlDateTime start_dt; start_dt.year=dt.year; start_dt.mon=3; start_dt.day=start_day; start_dt.hour=1; start_dt.min=0; start_dt.sec=0;
   MqlDateTime end_dt; end_dt.year=dt.year; end_dt.mon=10; end_dt.day=end_day; end_dt.hour=1; end_dt.min=0; end_dt.sec=0;
   return utc_time >= StructToTime(start_dt) && utc_time < StructToTime(end_dt);
}}

bool IsNewYorkDstUtc(const datetime utc_time)
{{
   MqlDateTime dt; TimeToStruct(utc_time,dt);
   int start_day=NthSunday(dt.year,3,2);
   int end_day=NthSunday(dt.year,11,1);
   MqlDateTime start_dt; start_dt.year=dt.year; start_dt.mon=3; start_dt.day=start_day; start_dt.hour=7; start_dt.min=0; start_dt.sec=0;
   MqlDateTime end_dt; end_dt.year=dt.year; end_dt.mon=11; end_dt.day=end_day; end_dt.hour=6; end_dt.min=0; end_dt.sec=0;
   return utc_time >= StructToTime(start_dt) && utc_time < StructToTime(end_dt);
}}

int BrokerUtcOffsetSeconds()
{{
   if(!InpUseAutoBrokerUtcOffset) return InpManualBrokerUtcOffsetHours*3600;
   datetime server=TimeTradeServer();
   datetime utc=TimeGMT();
   if(server <= 0 || utc <= 0) return InpManualBrokerUtcOffsetHours*3600;
   return (int)(server-utc);
}}

datetime ServerToUtc(const datetime server_time)
{{
   return server_time-BrokerUtcOffsetSeconds();
}}

string SessionName(const datetime utc_time)
{{
   MqlDateTime utc; TimeToStruct(utc_time,utc);
   int london_hour=(utc.hour+(IsLondonDstUtc(utc_time)?1:0))%24;
   int ny_hour=(utc.hour+(IsNewYorkDstUtc(utc_time)?-4:-5)+24)%24;
   if(ny_hour >= 8 && ny_hour < 17) return "new_york";
   if(london_hour >= 8 && london_hour < 13) return "london";
   if(utc.hour >= 0 && utc.hour < 7) return "asia";
   return "off_session";
}}

string AlignmentBand(const int score)
{{
   if(score >= 3) return "strong_up";
   if(score >= 1) return "up";
   if(score <= -3) return "strong_down";
   if(score <= -1) return "down";
   return "neutral";
}}

string CompressionBand(const double ratio)
{{
   if(ratio < 0.72) return "compressed";
   if(ratio > 1.35) return "expanded";
   return "normal";
}}

string TrendBand(const double trend)
{{
   if(trend >= 0.18) return "up";
   if(trend <= -0.18) return "down";
   return "flat";
}}

string StreakBand(const int streak)
{{
   if(streak >= 3) return "up3";
   if(streak <= -3) return "down3";
   return "short";
}}

string RegimeName(const double atr,const double average_range_12,const double compression_ratio,const double trend_12_atr)
{{
   if(compression_ratio < 0.72) return "compression";
   if(MathAbs(trend_12_atr) >= 0.18) return trend_12_atr > 0 ? "trend_up" : "trend_down";
   if(average_range_12 > 0 && atr >= average_range_12*1.25) return "high_volatility";
   return "range";
}}

bool GetRates(const ENUM_TIMEFRAMES timeframe,const int start_shift,const int count,MqlRates &rates[])
{{
   ArraySetAsSeries(rates,true);
   return CopyRates(_Symbol,timeframe,start_shift,count,rates) == count;
}}

double LinearSlopeChronological(const double &values[],const int count)
{{
   if(count < 2) return 0.0;
   double x_mean=(count-1)/2.0;
   double y_mean=0.0;
   for(int i=0;i<count;i++) y_mean+=values[i];
   y_mean/=count;
   double numerator=0.0,denominator=0.0;
   for(int i=0;i<count;i++)
   {{
      double dx=i-x_mean;
      numerator+=dx*(values[i]-y_mean);
      denominator+=dx*dx;
   }}
   return denominator > 0 ? numerator/denominator : 0.0;
}}

int CompletedCandleDirection(const ENUM_TIMEFRAMES timeframe)
{{
   double open=iOpen(_Symbol,timeframe,1);
   double close=iClose(_Symbol,timeframe,1);
   return SignDouble(close-open);
}}

int CalculateAlignmentScore()
{{
   return CompletedCandleDirection(PERIOD_M15)+CompletedCandleDirection(PERIOD_H1)+CompletedCandleDirection(PERIOD_H4)+CompletedCandleDirection(PERIOD_D1);
}}

bool CalculateFeatureSet(FeatureSet &f)
{{
   MqlRates bars[];
   if(!GetRates(PERIOD_M5,1,60,bars)) return false;
   double tr_sum=0.0;
   for(int i=0;i<14;i++)
   {{
      double previous_close=bars[i+1].close;
      double candle_range=bars[i].high-bars[i].low;
      double high_gap=MathAbs(bars[i].high-previous_close);
      double low_gap=MathAbs(bars[i].low-previous_close);
      tr_sum+=MathMax(candle_range,MathMax(high_gap,low_gap));
   }}
   f.atr_14=tr_sum/14.0;
   if(f.atr_14 <= 0) return false;

   datetime source_open=bars[0].time;
   datetime utc_time=ServerToUtc(source_open);
   MqlDateTime dt; TimeToStruct(utc_time,dt);
   f.weekday=dt.day_of_week == 0 ? 7 : dt.day_of_week;
   f.month=dt.mon;
   f.quarter=((dt.mon-1)/3)+1;
   f.week_of_month=((dt.day-1)/7)+1;
   f.hour_utc=dt.hour;
   f.session=SessionName(utc_time);
   f.direction=SignDouble(bars[0].close-bars[0].open);

   double range3=0.0,range12=0.0;
   for(int i=0;i<3;i++) range3+=bars[i].high-bars[i].low;
   for(int i=0;i<12;i++) range12+=bars[i].high-bars[i].low;
   double average_range_12=range12/12.0;
   f.compression_ratio=average_range_12 > 0 ? (range3/3.0)/average_range_12 : 1.0;
   f.compression_band=CompressionBand(f.compression_ratio);

   double closes[12];
   for(int i=0;i<12;i++) closes[i]=bars[11-i].close;
   f.trend_12_atr=LinearSlopeChronological(closes,12)/f.atr_14;
   f.trend_band=TrendBand(f.trend_12_atr);

   f.streak=0;
   int first_direction=0;
   for(int i=0;i<12;i++)
   {{
      int d=SignDouble(bars[i].close-bars[i].open);
      if(d == 0) break;
      if(first_direction == 0) first_direction=d;
      if(d != first_direction) break;
      f.streak+=d;
   }}
   f.streak_band=StreakBand(f.streak);

   f.alignment_score=CalculateAlignmentScore();
   f.alignment_band=AlignmentBand(f.alignment_score);
   f.regime=RegimeName(f.atr_14,average_range_12,f.compression_ratio,f.trend_12_atr);
   return true;
}}

bool SourceConditionMatched(const FeatureSet &f)
{{
   return {source_match};
}}

int StrategyDirection(const FeatureSet &f)
{{
   {direction_code}
}}

bool HasOurPosition()
{{
   for(int i=PositionsTotal()-1;i>=0;i--)
   {{
      ulong ticket=PositionGetTicket(i);
      if(ticket == 0 || !PositionSelectByTicket(ticket)) continue;
      if(PositionGetString(POSITION_SYMBOL) == _Symbol && PositionGetInteger(POSITION_MAGIC) == EVE_MAGIC) return true;
   }}
   return false;
}}

void ManageMaximumHold()
{{
   for(int i=PositionsTotal()-1;i>=0;i--)
   {{
      ulong ticket=PositionGetTicket(i);
      if(ticket == 0 || !PositionSelectByTicket(ticket)) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol || PositionGetInteger(POSITION_MAGIC) != EVE_MAGIC) continue;
      datetime opened=(datetime)PositionGetInteger(POSITION_TIME);
      if(TimeCurrent()-opened >= EVE_MAX_HOLD_MIN*60)
      {{
         trade.PositionClose(ticket,InpSlippagePoints);
         if(InpVerboseLogging) Print(EVE_STRATEGY_CODE,": time exit after ",EVE_MAX_HOLD_MIN," minutes");
      }}
   }}
}}

double ClosedProfitToday()
{{
   MqlDateTime now; TimeToStruct(TimeCurrent(),now);
   now.hour=0; now.min=0; now.sec=0;
   datetime day_start=StructToTime(now);
   if(!HistorySelect(day_start,TimeCurrent())) return 0.0;
   double result=0.0;
   int total=HistoryDealsTotal();
   for(int i=0;i<total;i++)
   {{
      ulong ticket=HistoryDealGetTicket(i);
      if(ticket == 0) continue;
      if(HistoryDealGetString(ticket,DEAL_SYMBOL) != _Symbol) continue;
      if((long)HistoryDealGetInteger(ticket,DEAL_MAGIC) != EVE_MAGIC) continue;
      long entry=(long)HistoryDealGetInteger(ticket,DEAL_ENTRY);
      if(entry != DEAL_ENTRY_OUT && entry != DEAL_ENTRY_OUT_BY) continue;
      result+=HistoryDealGetDouble(ticket,DEAL_PROFIT)+HistoryDealGetDouble(ticket,DEAL_SWAP)+HistoryDealGetDouble(ticket,DEAL_COMMISSION);
   }}
   return result;
}}

bool DailyLossGuardPassed()
{{
   if(InpMaxDailyLossPercent <= 0) return true;
   double balance=AccountInfoDouble(ACCOUNT_BALANCE);
   double limit=balance*InpMaxDailyLossPercent/100.0;
   return ClosedProfitToday() > -limit;
}}

double NormalizeVolume(double volume)
{{
   double min_lot=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN);
   double max_lot=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX);
   double step=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);
   if(step <= 0) step=min_lot;
   volume=MathMax(min_lot,MathMin(max_lot,volume));
   volume=MathFloor(volume/step+1e-9)*step;
   int digits=2;
   if(step < 0.01) digits=3;
   if(step < 0.001) digits=4;
   return NormalizeDouble(volume,digits);
}}

double CalculateVolume(const double stop_distance_price)
{{
   if(InpUseFixedLot) return NormalizeVolume(InpFixedLot);
   double balance=AccountInfoDouble(ACCOUNT_BALANCE);
   double risk_money=balance*InpRiskPercent/100.0;
   double tick_size=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_SIZE);
   double tick_value=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_VALUE_LOSS);
   if(tick_value <= 0) tick_value=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_VALUE);
   if(stop_distance_price <= 0 || tick_size <= 0 || tick_value <= 0) return NormalizeVolume(InpFixedLot);
   double loss_per_lot=(stop_distance_price/tick_size)*tick_value;
   if(loss_per_lot <= 0) return NormalizeVolume(InpFixedLot);
   return NormalizeVolume(risk_money/loss_per_lot);
}}

bool CooldownPassed()
{{
   string key="EVE_LAST_ENTRY_"+IntegerToString((int)EVE_MAGIC)+"_"+_Symbol;
   if(GlobalVariableCheck(key)) last_entry_time=(datetime)GlobalVariableGet(key);
   return last_entry_time == 0 || TimeCurrent()-last_entry_time >= EVE_COOLDOWN_MIN*60;
}}

void SaveEntryTime()
{{
   last_entry_time=TimeCurrent();
   string key="EVE_LAST_ENTRY_"+IntegerToString((int)EVE_MAGIC)+"_"+_Symbol;
   GlobalVariableSet(key,(double)last_entry_time);
}}

bool SpreadPassed()
{{
   MqlTick tick;
   if(!SymbolInfoTick(_Symbol,tick)) return false;
   double spread_points=(tick.ask-tick.bid)/_Point;
   return InpMaxSpreadPoints <= 0 || spread_points <= InpMaxSpreadPoints;
}}

void EvaluateNewSignal()
{{
   if(!InpEnableTrading) return;
   if(HasOurPosition() || !CooldownPassed() || !SpreadPassed() || !DailyLossGuardPassed()) return;

   datetime source_time=iTime(_Symbol,PERIOD_M5,1);
   if(source_time <= 0) return;
   MqlDateTime source_utc; TimeToStruct(ServerToUtc(source_time),source_utc);
   if(source_utc.min % 15 != 0) return; // Matches EVE's 15-minute research snapshot anchors.

   FeatureSet f;
   if(!CalculateFeatureSet(f)) return;
   bool matched=SourceConditionMatched(f);
   bool eligible=EVE_CONDITION_INCLUDE ? matched : !matched;
   if(!eligible) return;

   int direction=StrategyDirection(f);
   if(direction > 0 && !InpAllowLong) return;
   if(direction < 0 && !InpAllowShort) return;
   if(direction == 0) return;

   MqlTick tick;
   if(!SymbolInfoTick(_Symbol,tick)) return;
   double stop_distance=EVE_STOP_ATR*f.atr_14;
   double target_distance=EVE_TARGET_ATR*f.atr_14;
   double volume=CalculateVolume(stop_distance);
   if(volume <= 0) return;

   int digits=(int)SymbolInfoInteger(_Symbol,SYMBOL_DIGITS);
   double price=direction > 0 ? tick.ask : tick.bid;
   double stop=direction > 0 ? price-stop_distance : price+stop_distance;
   double target=direction > 0 ? price+target_distance : price-target_distance;
   stop=NormalizeDouble(stop,digits);
   target=NormalizeDouble(target,digits);

   trade.SetExpertMagicNumber(EVE_MAGIC);
   trade.SetDeviationInPoints(InpSlippagePoints);
   trade.SetTypeFillingBySymbol(_Symbol);
   string comment=EVE_STRATEGY_CODE+" "+StringSubstr(EVE_RULE_HASH,0,8);
   bool opened=direction > 0
      ? trade.Buy(volume,_Symbol,0.0,stop,target,comment)
      : trade.Sell(volume,_Symbol,0.0,stop,target,comment);
   if(opened)
   {{
      SaveEntryTime();
      Print(EVE_STRATEGY_CODE,": opened ",direction > 0 ? "BUY" : "SELL"," lots=",DoubleToString(volume,2)," ATR=",DoubleToString(f.atr_14,digits)," rule_hash=",EVE_RULE_HASH);
   }}
   else
   {{
      Print(EVE_STRATEGY_CODE,": order failed code=",trade.ResultRetcode()," ",trade.ResultRetcodeDescription());
   }}
}}

int OnInit()
{{
   trade.SetExpertMagicNumber(EVE_MAGIC);
   last_m5_bar=iTime(_Symbol,PERIOD_M5,0);
   Print(EVE_STRATEGY_CODE,": loaded. Frozen hash=",EVE_RULE_HASH,". InpEnableTrading defaults to FALSE for safety.");
   return INIT_SUCCEEDED;
}}

void OnDeinit(const int reason)
{{
}}

void OnTick()
{{
   ManageMaximumHold();
   datetime current=iTime(_Symbol,PERIOD_M5,0);
   if(current <= 0 || current == last_m5_bar) return;
   last_m5_bar=current;
   EvaluateNewSignal();
}}
'''
    return source


def static_validate_mq5(source: str, frozen: dict[str, Any]) -> list[str]:
    issues: list[str] = []
    required = [
        "#property strict",
        "int OnInit()",
        "void OnTick()",
        "InpEnableTrading             = false",
        "EVE_RULE_HASH",
        "SourceConditionMatched",
        "CalculateFeatureSet",
        "ManageMaximumHold",
        "DailyLossGuardPassed",
        "M1",  # present in header/report context; prevents an empty template slipping through
    ]
    for token in required:
        if token not in source:
            issues.append(f"Missing required source token: {token}")
    rule_hash = str(frozen.get("rule_hash") or "")
    if rule_hash and rule_hash not in source:
        issues.append("Frozen rule hash is not embedded in the EA source")
    if source.count("{") != source.count("}"):
        issues.append("Unbalanced braces in generated MQL5 source")
    if "TODO" in source or "PLACEHOLDER" in source:
        issues.append("Generated source contains an unresolved placeholder")
    return issues


def build_readme(frozen: dict[str, Any], file_name: str) -> str:
    metrics = dict(frozen.get("validation_metrics") or {})
    standard = dict(metrics.get("standard_cost") or {})
    locked = dict(standard.get("locked_test") or {})
    rules = dict(frozen.get("rules") or {})
    summary = plain_rule_summary(rules)
    return f"""EVE ALGO LAB — MT5 PACKAGE

Strategy: {frozen.get('name')}
Strategy code: {frozen.get('strategy_code')}
Frozen version: {frozen.get('version')}
Rules SHA-256: {frozen.get('rule_hash')}
Generated by: EVE Algo Lab v2.5

THIS PACKAGE IS FOR METAEDITOR COMPILATION AND DEMO FORWARD TESTING ONLY.
DO NOT PLACE IT ON A LIVE ACCOUNT.

FROZEN RULES
- Plain-English rule: {summary}
- Condition mode: {rules.get('condition_mode')}
- Direction rule: {rules.get('direction_rule')}
- Stop: {number(rules.get('stop_atr')):.2f} ATR
- Target: {number(rules.get('target_atr')):.2f} ATR
- Maximum hold: {int(number(rules.get('horizon_minutes')))} minutes
- Cooldown: {int(number(rules.get('cooldown_minutes')))} minutes

WHEN TO ATTACH
Open EVE Algo Lab > Demo Lab. EVE reads this exact frozen rule set and labels it:
- TEST NOW: the current tested window and live context are eligible.
- ATTACH AND LEAVE: attach on demo; the EA is waiting for its market condition.
- WAIT FOR TIME: the required UTC hour or session is not active yet.
- WAIT FOR PERIOD: the required weekday, week, month or quarter is not active.
- MARKET CLOSED: wait until the estimated gold-market reopen.

M1 LOCKED EVIDENCE
- Profit factor: {number(locked.get('profit_factor')):.2f}
- Expectancy: {number(locked.get('expectancy_r')):+.3f}R
- Trades: {int(number(locked.get('trades')))}
- Maximum drawdown: {number(locked.get('max_drawdown_r')):.2f}R

INSTALLATION
1. In MT5 choose File > Open Data Folder.
2. Open MQL5 > Experts.
3. Copy {file_name} into the Experts folder.
4. Open MetaEditor and compile the .mq5 file.
5. Fix no code or rule values. A code change creates an unvalidated strategy.
6. Check EVE Demo Lab before choosing the EA.
7. Attach the EA to an XAUUSD M5 chart on a DEMO account.
8. Check broker UTC offset. The EA can auto-detect it, with a manual input available.
9. Keep InpEnableTrading=false until inputs and chart are verified.
10. Turn InpEnableTrading=true only on demo.
11. Enable Algo Trading and monitor the Experts and Journal tabs.

IMPORTANT DATA-PARITY NOTE
EVE validation used Twelve Data candles. MT5 execution uses the broker's own XAUUSD feed.
Small differences in candle boundaries, spreads, daily bars and prices are expected.
That is why demo forward testing is mandatory.

PACKAGE CONTENTS
- {file_name}: generated Expert Advisor source
- FROZEN_RULES.json: immutable rules
- VALIDATION_REPORT.json: evidence used for generation
- MANIFEST.json: package identity and checksums
- README.txt: this file
"""


def upgrade_source_for_fleet(source: str, package_id: str, rule_hash: str, secret: str) -> str:
    """Add best-effort Demo Fleet telemetry without changing frozen trade rules.

    Stored packages remain immutable. Download routes add this operational wrapper
    so existing and future packages can report whether they are attached to MT5.
    Heartbeats are never used as an entry, exit or risk-management condition.
    """
    if "EVE_FLEET_TELEMETRY_V31" in source:
        return source
    token = fleet_token(secret, package_id, rule_hash)
    upgraded = re.sub(r'#property\s+version\s+"[^"]+"', '#property version   "3.10"', source, count=1)
    upgraded = upgraded.replace(
        'input bool   InpVerboseLogging            = true;\n',
        'input bool   InpVerboseLogging            = true;\n'
        'input bool   InpFleetTelemetry             = true;    // Attachment status only; never controls trading\n'
        'input string InpFleetEndpoint              = "https://evealgolab.netlify.app/api/fleet/heartbeat";\n'
        'input int    InpFleetHeartbeatSeconds      = 30;\n',
        1,
    )
    upgraded = upgraded.replace(
        'const bool   EVE_CONDITION_INCLUDE = ',
        f'const string EVE_PACKAGE_ID     = "{mql_string(package_id)}";\n'
        f'const string EVE_FLEET_TOKEN    = "{mql_string(token)}";\n'
        'const string EVE_FLEET_VERSION  = "3.1";\n'
        'const bool   EVE_CONDITION_INCLUDE = ',
        1,
    )
    upgraded = upgraded.replace(
        'datetime last_entry_time = 0;\n',
        'datetime last_entry_time = 0;\n'
        'string fleet_state = "starting";\n'
        'string fleet_state_detail = "EA initialising";\n'
        'datetime fleet_last_send = 0;\n'
        '// EVE_FLEET_TELEMETRY_V31\n',
        1,
    )

    telemetry = r'''
string JsonEscape(string value)
{
   StringReplace(value,"\\","\\\\");
   StringReplace(value,"\"","\\\"");
   StringReplace(value,"\r"," ");
   StringReplace(value,"\n"," ");
   return value;
}

string JsonBool(const bool value)
{
   return value ? "true" : "false";
}

string FleetAccountType()
{
   long mode=AccountInfoInteger(ACCOUNT_TRADE_MODE);
   if(mode == ACCOUNT_TRADE_MODE_DEMO) return "demo";
   if(mode == ACCOUNT_TRADE_MODE_CONTEST) return "contest";
   if(mode == ACCOUNT_TRADE_MODE_REAL) return "real";
   return "unknown";
}

int FleetOpenPositions()
{
   int count=0;
   for(int i=PositionsTotal()-1;i>=0;i--)
   {
      ulong ticket=PositionGetTicket(i);
      if(ticket == 0 || !PositionSelectByTicket(ticket)) continue;
      if(PositionGetString(POSITION_SYMBOL) == _Symbol && PositionGetInteger(POSITION_MAGIC) == EVE_MAGIC) count++;
   }
   return count;
}

double FleetOpenProfit()
{
   double result=0.0;
   for(int i=PositionsTotal()-1;i>=0;i--)
   {
      ulong ticket=PositionGetTicket(i);
      if(ticket == 0 || !PositionSelectByTicket(ticket)) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol || PositionGetInteger(POSITION_MAGIC) != EVE_MAGIC) continue;
      result+=PositionGetDouble(POSITION_PROFIT)+PositionGetDouble(POSITION_SWAP);
   }
   return result;
}

datetime FleetLastTradeTime()
{
   if(!HistorySelect(0,TimeCurrent())) return 0;
   datetime latest=0;
   int total=HistoryDealsTotal();
   for(int i=total-1;i>=0;i--)
   {
      ulong ticket=HistoryDealGetTicket(i);
      if(ticket == 0) continue;
      if(HistoryDealGetString(ticket,DEAL_SYMBOL) != _Symbol) continue;
      if((long)HistoryDealGetInteger(ticket,DEAL_MAGIC) != EVE_MAGIC) continue;
      datetime value=(datetime)HistoryDealGetInteger(ticket,DEAL_TIME);
      if(value > latest) latest=value;
   }
   return latest;
}

void SetFleetState(const string state,const string detail)
{
   fleet_state=state;
   fleet_state_detail=detail;
}

void SendFleetHeartbeat(const bool force=false)
{
   if(!InpFleetTelemetry || MQLInfoInteger(MQL_TESTER)) return;
   int interval=InpFleetHeartbeatSeconds < 10 ? 10 : InpFleetHeartbeatSeconds;
   if(!force && fleet_last_send > 0 && TimeCurrent()-fleet_last_send < interval) return;

   bool terminal_allowed=(bool)TerminalInfoInteger(TERMINAL_TRADE_ALLOWED);
   bool ea_allowed=(bool)MQLInfoInteger(MQL_TRADE_ALLOWED);
   string payload="{";
   payload+="\"package_id\":\""+JsonEscape(EVE_PACKAGE_ID)+"\",";
   payload+="\"strategy_code\":\""+JsonEscape(EVE_STRATEGY_CODE)+"\",";
   payload+="\"rule_hash\":\""+JsonEscape(EVE_RULE_HASH)+"\",";
   payload+="\"account_login\":"+IntegerToString((long)AccountInfoInteger(ACCOUNT_LOGIN))+",";
   payload+="\"account_type\":\""+FleetAccountType()+"\",";
   payload+="\"broker_server\":\""+JsonEscape(AccountInfoString(ACCOUNT_SERVER))+"\",";
   payload+="\"broker_company\":\""+JsonEscape(AccountInfoString(ACCOUNT_COMPANY))+"\",";
   payload+="\"symbol\":\""+JsonEscape(_Symbol)+"\",";
   payload+="\"timeframe\":\""+JsonEscape(EnumToString((ENUM_TIMEFRAMES)_Period))+"\",";
   payload+="\"chart_id\":\""+IntegerToString(ChartID())+"\",";
   payload+="\"trading_enabled\":"+JsonBool(InpEnableTrading)+",";
   payload+="\"algo_trading_enabled\":"+JsonBool(terminal_allowed && ea_allowed)+",";
   payload+="\"state\":\""+JsonEscape(fleet_state)+"\",";
   payload+="\"state_detail\":\""+JsonEscape(fleet_state_detail)+"\",";
   payload+="\"open_positions\":"+IntegerToString(FleetOpenPositions())+",";
   payload+="\"open_profit\":"+DoubleToString(FleetOpenProfit(),2)+",";
   payload+="\"closed_profit_today\":"+DoubleToString(ClosedProfitToday(),2)+",";
   payload+="\"terminal_time\":"+IntegerToString((long)TimeCurrent())+",";
   payload+="\"last_trade_time\":"+IntegerToString((long)FleetLastTradeTime())+",";
   payload+="\"client_version\":\""+EVE_FLEET_VERSION+"\"";
   payload+="}";

   char data[];
   int data_size=StringToCharArray(payload,data,0,WHOLE_ARRAY,CP_UTF8);
   if(data_size > 0) ArrayResize(data,data_size-1);
   char result[];
   string response_headers;
   string headers="Content-Type: application/json\r\nX-EVE-FLEET-TOKEN: "+EVE_FLEET_TOKEN+"\r\n";
   ResetLastError();
   int response=WebRequest("POST",InpFleetEndpoint,headers,1000,data,result,response_headers);
   fleet_last_send=TimeCurrent();
   if(response < 200 || response >= 300)
   {
      if(force && InpVerboseLogging) Print(EVE_STRATEGY_CODE,": Demo Fleet heartbeat unavailable HTTP=",response," MQL=",GetLastError(),". Trading continues normally.");
   }
}
'''
    upgraded = upgraded.replace('void EvaluateNewSignal()\n{', telemetry + '\nvoid EvaluateNewSignal()\n{', 1)
    upgraded = upgraded.replace(
        '   if(!InpEnableTrading) return;\n   if(HasOurPosition() || !CooldownPassed() || !SpreadPassed() || !DailyLossGuardPassed()) return;\n',
        '   if(!InpEnableTrading) { SetFleetState("trading_disabled","Enable the EA safety input on demo"); return; }\n'
        '   if(HasOurPosition()) { SetFleetState("position_open","Managing the current position"); return; }\n'
        '   if(!CooldownPassed()) { SetFleetState("cooldown","Waiting for the frozen cooldown"); return; }\n'
        '   if(!SpreadPassed()) { SetFleetState("spread_blocked","Spread is above the safety limit"); return; }\n'
        '   if(!DailyLossGuardPassed()) { SetFleetState("daily_loss_guard","Daily loss safety guard is active"); return; }\n',
        1,
    )
    upgraded = upgraded.replace('   if(source_time <= 0) return;\n', '   if(source_time <= 0) { SetFleetState("waiting_data","Waiting for M5 chart data"); return; }\n', 1)
    upgraded = upgraded.replace("   if(source_utc.min % 15 != 0) return; // Matches EVE's 15-minute research snapshot anchors.\n", "   if(source_utc.min % 15 != 0) { SetFleetState(\"waiting_anchor\",\"Waiting for the next 15-minute checkpoint\"); return; } // Matches EVE's 15-minute research snapshot anchors.\n", 1)
    upgraded = upgraded.replace('   if(!CalculateFeatureSet(f)) return;\n', '   if(!CalculateFeatureSet(f)) { SetFleetState("waiting_data","Not enough data to calculate the frozen features"); return; }\n', 1)
    upgraded = upgraded.replace('   if(!eligible) return;\n', '   if(!eligible) { SetFleetState("waiting_rule_condition","Waiting for the frozen day, time or market condition"); return; }\n', 1)
    upgraded = upgraded.replace(
        '   if(direction > 0 && !InpAllowLong) return;\n   if(direction < 0 && !InpAllowShort) return;\n   if(direction == 0) return;\n',
        '   if(direction > 0 && !InpAllowLong) { SetFleetState("direction_blocked","Long entries are disabled in Inputs"); return; }\n'
        '   if(direction < 0 && !InpAllowShort) { SetFleetState("direction_blocked","Short entries are disabled in Inputs"); return; }\n'
        '   if(direction == 0) { SetFleetState("waiting_direction","Waiting for a non-neutral frozen direction"); return; }\n',
        1,
    )
    upgraded = upgraded.replace(
        '      SaveEntryTime();\n      Print(EVE_STRATEGY_CODE,": opened ",',
        '      SaveEntryTime();\n      SetFleetState("position_open",direction > 0 ? "BUY opened" : "SELL opened");\n      SendFleetHeartbeat(true);\n      Print(EVE_STRATEGY_CODE,": opened ",',
        1,
    )
    upgraded = upgraded.replace(
        '      Print(EVE_STRATEGY_CODE,": order failed code=",trade.ResultRetcode()," ",trade.ResultRetcodeDescription());\n',
        '      SetFleetState("order_failed",trade.ResultRetcodeDescription());\n      SendFleetHeartbeat(true);\n      Print(EVE_STRATEGY_CODE,": order failed code=",trade.ResultRetcode()," ",trade.ResultRetcodeDescription());\n',
        1,
    )
    upgraded = upgraded.replace(
        '         trade.PositionClose(ticket,InpSlippagePoints);\n         if(InpVerboseLogging)',
        '         trade.PositionClose(ticket,InpSlippagePoints);\n         SetFleetState("time_exit","Position closed at the frozen maximum hold");\n         SendFleetHeartbeat(true);\n         if(InpVerboseLogging)',
        1,
    )
    upgraded = upgraded.replace(
        '   Print(EVE_STRATEGY_CODE,": loaded. Frozen hash=",EVE_RULE_HASH,". InpEnableTrading defaults to FALSE for safety.");\n   return INIT_SUCCEEDED;\n',
        '   int heartbeat_seconds=InpFleetHeartbeatSeconds < 10 ? 10 : InpFleetHeartbeatSeconds;\n'
        '   EventSetTimer(heartbeat_seconds);\n'
        '   SetFleetState(InpEnableTrading ? "running" : "trading_disabled",InpEnableTrading ? "EA attached and monitoring" : "Enable the EA safety input on demo");\n'
        '   SendFleetHeartbeat(true);\n'
        '   Print(EVE_STRATEGY_CODE,": loaded. Frozen hash=",EVE_RULE_HASH,". InpEnableTrading defaults to FALSE for safety.");\n'
        '   return INIT_SUCCEEDED;\n',
        1,
    )
    upgraded = upgraded.replace(
        'void OnDeinit(const int reason)\n{\n}\n',
        'void OnDeinit(const int reason)\n{\n   SetFleetState("detached","EA removed or MT5 closing");\n   SendFleetHeartbeat(true);\n   EventKillTimer();\n}\n\nvoid OnTimer()\n{\n   if(HasOurPosition()) SetFleetState("position_open","Managing the current position");\n   else if(InpEnableTrading && fleet_state == "position_open") SetFleetState("running","Position finished; waiting for the next frozen setup");\n   SendFleetHeartbeat(false);\n}\n',
        1,
    )
    upgraded = upgraded.replace(
        '   ManageMaximumHold();\n   datetime current=iTime(_Symbol,PERIOD_M5,0);\n',
        '   ManageMaximumHold();\n   if(HasOurPosition()) SetFleetState("position_open","Managing the current position");\n   datetime current=iTime(_Symbol,PERIOD_M5,0);\n',
        1,
    )
    required_markers = (
        "EVE_FLEET_TELEMETRY_V31",
        "input bool   InpFleetTelemetry",
        "const string EVE_PACKAGE_ID",
        "void SendFleetHeartbeat",
        "void OnTimer()",
        "WebRequest",
    )
    missing = [marker for marker in required_markers if marker not in upgraded]
    if missing:
        raise ValueError(f"Fleet telemetry could not be added safely; missing source anchors: {', '.join(missing)}")
    if upgraded.count("trade.Buy") != source.count("trade.Buy") or upgraded.count("trade.Sell") != source.count("trade.Sell"):
        raise ValueError("Fleet telemetry upgrade changed the EA order-execution call count")
    return upgraded


def prepare_package_for_download(package: dict[str, Any], secret: str) -> dict[str, Any]:
    prepared = dict(package)
    package_id = str(package.get("id") or "")
    rule_hash = str(package.get("rule_hash") or "")
    source = upgrade_source_for_fleet(str(package.get("mq5_source") or ""), package_id, rule_hash, secret)
    manifest = dict(package.get("manifest") or {})
    manifest.update({
        "command_centre_version": "3.1",
        "fleet_telemetry": True,
        "fleet_endpoint": "https://evealgolab.netlify.app/api/fleet/heartbeat",
        "fleet_note": "Best-effort telemetry is never used as a trading condition.",
        "execution_source_sha256": sha256_text(source),
    })
    readme = str(package.get("readme_text") or "")
    if "DEMO FLEET CONNECTION" not in readme:
        readme += """

DEMO FLEET CONNECTION
- This download includes best-effort EVE Command Centre heartbeat telemetry.
- In MT5 open Tools > Options > Expert Advisors.
- Tick Allow WebRequest for listed URL and add: https://evealgolab.netlify.app
- Telemetry reports attachment state, chart, demo account type and P/L only.
- A telemetry or internet failure never blocks, changes or closes a trade.
- Demo Fleet marks the bot offline automatically when MT5 or the EA stops reporting.
"""
    prepared["mq5_source"] = source
    prepared["manifest"] = manifest
    prepared["readme_text"] = readme
    prepared["source_sha256"] = sha256_text(source)
    return prepared

def build_package_files(package: dict[str, Any]) -> dict[str, bytes]:
    source = str(package.get("mq5_source") or "")
    file_name = str(package.get("file_name") or "EVE_Strategy.mq5")
    frozen_rules = package.get("frozen_rules") or {}
    validation_report = package.get("validation_report") or {}
    manifest = package.get("manifest") or {}
    readme = str(package.get("readme_text") or "")
    return {
        file_name: source.encode("utf-8"),
        "FROZEN_RULES.json": json.dumps(frozen_rules, indent=2, sort_keys=True, default=str).encode("utf-8"),
        "VALIDATION_REPORT.json": json.dumps(validation_report, indent=2, sort_keys=True, default=str).encode("utf-8"),
        "MANIFEST.json": json.dumps(manifest, indent=2, sort_keys=True, default=str).encode("utf-8"),
        "README.txt": readme.encode("utf-8"),
    }


def build_package_zip(package: dict[str, Any]) -> bytes:
    buffer = io.BytesIO()
    files = build_package_files(package)
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for name, content in files.items():
            archive.writestr(name, content)
        checksums = "\n".join(f"{hashlib.sha256(content).hexdigest()}  {name}" for name, content in files.items()) + "\n"
        archive.writestr("SHA256SUMS.txt", checksums)
    return buffer.getvalue()


def generation_key(frozen: dict[str, Any]) -> str:
    identity = {
        "generator": MT5_GENERATOR_VERSION,
        "frozen_strategy_id": frozen.get("id"),
        "rule_hash": frozen.get("rule_hash"),
        "version": frozen.get("version"),
    }
    return f"mt5-{hashlib.sha256(canonical(identity).encode()).hexdigest()[:28]}"


def generate_package_payload(frozen: dict[str, Any]) -> dict[str, Any]:
    source = generate_mq5_source(frozen)
    issues = static_validate_mq5(source, frozen)
    if issues:
        raise ValueError("; ".join(issues))
    strategy_code = str(frozen.get("strategy_code") or "EVE-STRATEGY")
    version = str(frozen.get("version") or "1.0")
    version_token = re.sub(r"[^A-Za-z0-9]+", "_", version).strip("_") or "1_0"
    file_name = f"{safe_name(strategy_code)}_v{version_token}.mq5"
    source_sha = sha256_text(source)
    validation_report = {
        "strategy_code": strategy_code,
        "name": frozen.get("name"),
        "version": version,
        "rule_hash": frozen.get("rule_hash"),
        "source_validation_job_id": frozen.get("source_validation_job_id"),
        "validation_metrics": frozen.get("validation_metrics") or {},
        "validation_evidence": frozen.get("validation_evidence") or {},
        "generated_at": utc_now().isoformat(),
        "generator_version": MT5_GENERATOR_VERSION,
        "status": "ready_for_metaeditor_compile",
        "warning": "Generated source must compile in MetaEditor and pass demo forward testing before any live consideration.",
    }
    manifest = {
        "package_format": "eve-mt5-package-v2",
        "generator_version": MT5_GENERATOR_VERSION,
        "strategy_code": strategy_code,
        "strategy_name": frozen.get("name"),
        "frozen_version": version,
        "rule_hash": frozen.get("rule_hash"),
        "source_sha256": source_sha,
        "file_name": file_name,
        "symbol_research": frozen.get("symbol") or "XAU/USD",
        "chart_timeframe": "M5",
        "safety_default": "InpEnableTrading=false",
        "deployment_stage": "demo_only",
        "eligibility_lab": "https://evealgolab.netlify.app/#demo-lab",
        "attach_timeframe": "M5",
        "plain_rule_summary": plain_rule_summary(frozen.get("rules") or {}),
    }
    readme = build_readme(frozen, file_name)
    package_code = f"{strategy_code}-MT5-v{version}"
    return {
        "package_code": package_code,
        "strategy_code": strategy_code,
        "version": version,
        "file_name": file_name,
        "mq5_source": source,
        "readme_text": readme,
        "frozen_rules": frozen.get("rules") or {},
        "validation_report": validation_report,
        "manifest": manifest,
        "source_sha256": source_sha,
        "static_validation": {"passed": True, "issues": []},
        "status": "ready_for_metaeditor_compile",
    }


class MT5GeneratorService:
    def __init__(self, settings: Settings, repo: SupabaseRepository) -> None:
        self.settings = settings
        self.repo = repo
        self.worker_id = f"mt5-generator-{socket.gethostname()}-{uuid.uuid4().hex[:8]}"
        self._stop = asyncio.Event()
        self._wake = asyncio.Event()

    async def stop(self) -> None:
        self._stop.set()
        self._wake.set()

    async def request_wake(self) -> None:
        self._wake.set()

    async def loop(self) -> None:
        if not self.settings.mt5_generator_enabled:
            logger.info("MT5 generator is disabled")
            return
        logger.info("MT5 generator worker %s started", self.worker_id)
        try:
            await asyncio.wait_for(self._stop.wait(), timeout=self.settings.mt5_generator_startup_delay_seconds)
            return
        except asyncio.TimeoutError:
            pass

        while not self._stop.is_set():
            try:
                await self.repo.upsert_mt5_generation_state(
                    "XAU/USD", status="active", worker_id=self.worker_id,
                    heartbeat_at=utc_now().isoformat(), started_at=utc_now().isoformat(), last_error=None,
                )
                await self.repo.reset_stale_mt5_generation_jobs()
                await self._ensure_queue()
                job = await self.repo.claim_next_mt5_generation_job(self.worker_id)
                if job:
                    await self._execute(job)
                else:
                    await self._sleep(self.settings.mt5_generator_idle_seconds)
                    continue
            except asyncio.CancelledError:
                raise
            except Exception as exc:
                logger.exception("MT5 generation cycle failed")
                await self.repo.upsert_mt5_generation_state(
                    "XAU/USD", status="error", heartbeat_at=utc_now().isoformat(),
                    last_error=str(exc)[:4000], last_result="MT5 generator recovered from an error and will retry automatically.",
                )
                await self._sleep(max(60.0, self.settings.mt5_generator_idle_seconds))
            await self._sleep(self.settings.mt5_generator_job_delay_seconds)

    async def _sleep(self, seconds: float) -> None:
        self._wake.clear()
        stop_task = asyncio.create_task(self._stop.wait())
        wake_task = asyncio.create_task(self._wake.wait())
        _, pending = await asyncio.wait({stop_task, wake_task}, timeout=max(1.0, seconds), return_when=asyncio.FIRST_COMPLETED)
        for task in pending:
            task.cancel()
        await asyncio.gather(*pending, return_exceptions=True)

    async def _ensure_queue(self) -> None:
        await self.repo.refresh_mt5_generation_state("XAU/USD")
        state = await self.repo.get_mt5_generation_state("XAU/USD") or {}
        if int(number(state.get("queue_count"))) >= self.settings.mt5_generator_queue_floor:
            return
        frozen = await self.repo.list_mt5_generation_seeds("XAU/USD", limit=MAX_GENERATION_SEEDS)
        rows = []
        for item in frozen:
            rows.append({
                "generation_key": generation_key(item),
                "symbol": item.get("symbol") or "XAU/USD",
                "frozen_strategy_id": item.get("id"),
                "strategy_code": item.get("strategy_code"),
                "strategy_name": item.get("name"),
                "frozen_version": item.get("version") or "1.0",
                "rule_hash": item.get("rule_hash"),
                "priority": 95,
                "status": "queued",
            })
        if rows:
            await self.repo.upsert_mt5_generation_jobs(rows)
            await self.repo.upsert_mt5_generation_state(
                "XAU/USD", status="active", last_generation_at=utc_now().isoformat(),
                last_result=f"Queued {len(rows)} frozen strategies for automatic MT5 source generation.",
            )
        else:
            await self.repo.upsert_mt5_generation_state(
                "XAU/USD", last_result="Waiting for a frozen strategy marked Ready for MT5 Generation.",
            )
        await self.repo.refresh_mt5_generation_state("XAU/USD")

    async def _execute(self, job: dict[str, Any]) -> None:
        job_id = str(job["id"])
        frozen_id = str(job.get("frozen_strategy_id") or "")
        name = str(job.get("strategy_name") or job.get("strategy_code") or "EVE strategy")
        await self.repo.upsert_mt5_generation_state(
            "XAU/USD", status="generating", worker_id=self.worker_id, heartbeat_at=utc_now().isoformat(),
            current_job_id=job_id, current_job_name=name, last_job_started_at=utc_now().isoformat(), last_error=None,
        )
        try:
            frozen = await self.repo.get_frozen_strategy(frozen_id)
            if not frozen:
                raise RuntimeError("Frozen strategy no longer exists")
            payload = generate_package_payload(frozen)
            package = await self.repo.create_mt5_package(job, frozen, payload)
            await self.repo.complete_mt5_generation_job(
                job_id,
                package_id=package.get("id"),
                file_name=payload["file_name"],
                source_sha256=payload["source_sha256"],
                result_status="generated",
                evidence={
                    "verdict": "Generated from immutable frozen rules. Ready for MetaEditor compilation and MT5 demo forward testing.",
                    "safety": "The EA defaults to InpEnableTrading=false and must not be used on live money.",
                },
            )
            await self.repo.mark_frozen_strategy_mt5_generated(frozen_id)
            await self.repo.upsert_mt5_generation_state(
                "XAU/USD", status="active", heartbeat_at=utc_now().isoformat(), current_job_id=None,
                current_job_name=None, last_job_finished_at=utc_now().isoformat(),
                last_result=f"Generated MT5 package {payload['package_code']} from frozen rules.", last_error=None,
            )
            await self.repo.log_event(
                "success", "mt5-generator", "MT5 package generated",
                {"strategy": name, "package_id": package.get("id"), "source_sha256": payload["source_sha256"]},
            )
            await self.repo.refresh_mt5_generation_state("XAU/USD")
        except Exception as exc:
            await self.repo.fail_mt5_generation_job(job_id, str(exc))
            await self.repo.upsert_mt5_generation_state(
                "XAU/USD", status="error", heartbeat_at=utc_now().isoformat(), current_job_id=None,
                current_job_name=None, last_job_finished_at=utc_now().isoformat(), last_error=str(exc)[:4000],
                last_result=f"MT5 generation failed safely for {name}. Frozen rules were not changed.",
            )
            raise
