-- EVE Algo Lab v1.2 — Fixed Ladder v2.61 backtester storage
-- Run this one file once in Supabase SQL Editor before deploying v1.2.

create table if not exists public.backtest_baskets (
  id bigint generated by default as identity primary key,
  backtest_run_id uuid not null references public.backtest_runs(id) on delete cascade,
  basket_id text not null,
  opened_at timestamptz not null,
  closed_at timestamptz not null,
  side text not null check (side in ('buy','sell','mixed','none')),
  positions integer not null default 0,
  gross_pnl numeric(18,6) not null default 0,
  costs numeric(18,6) not null default 0,
  net_pnl numeric(18,6) not null default 0,
  peak_floating numeric(18,6) not null default 0,
  worst_floating numeric(18,6) not null default 0,
  max_positions integer not null default 0,
  exit_reason text,
  metadata jsonb not null default '{}'::jsonb,
  unique (backtest_run_id, basket_id)
);

create index if not exists backtest_baskets_run_idx
  on public.backtest_baskets (backtest_run_id, opened_at desc);

alter table public.backtest_baskets enable row level security;

-- No public policies are created. Railway uses the service-role key.
